package com.trademaster.ims.mobile.auth;

import com.trademaster.ims.mobile.auth.dto.CustomerAuthDtos.*;
import com.trademaster.ims.mobile.auth.model.*;
import com.trademaster.ims.mobile.auth.repository.*;
import com.trademaster.ims.mobile.auth.security.CustomerJwtService;
import com.trademaster.ims.mobile.auth.service.*;
import com.trademaster.ims.model.Customer;
import com.trademaster.ims.repository.CustomerRepository;
import org.junit.jupiter.api.*;
import org.mockito.*;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class CustomerAuthServiceTest {
 @Mock CustomerAccountRepository accounts; @Mock CustomerRepository customers; @Mock CustomerAuthOtpRepository otps; @Mock CustomerRefreshTokenRepository refresh; @Mock CustomerResetAuthorizationRepository resets; @Mock CustomerJwtService jwt; @Mock CustomerAuthMailService mail;
 AutoCloseable mocks; CustomerAuthService service; BCryptPasswordEncoder encoder; AtomicLong ids; String deliveredOtp;
 @BeforeEach void setup(){mocks=MockitoAnnotations.openMocks(this);encoder=new BCryptPasswordEncoder(4);service=new CustomerAuthService(accounts,customers,otps,refresh,resets,encoder,jwt,mail);for(String f:new String[]{"otpMinutes","resendCooldown","refreshDays","resetMinutes","lockoutMinutes"})ReflectionTestUtils.setField(service,f,f.equals("refreshDays")?30L:f.equals("resendCooldown")?45L:f.equals("lockoutMinutes")?15L:10L);ReflectionTestUtils.setField(service,"otpMaxAttempts",5);ReflectionTestUtils.setField(service,"maxResends",5);ReflectionTestUtils.setField(service,"maxLoginFailures",5);ids=new AtomicLong(1);when(customers.save(any())).thenAnswer(i->{Customer c=i.getArgument(0);if(c.getCustomerId()==null)c.setCustomerId(ids.getAndIncrement());return c;});when(accounts.save(any())).thenAnswer(i->{CustomerAccount a=i.getArgument(0);if(a.getId()==null)a.setId(ids.getAndIncrement());return a;});when(otps.save(any())).thenAnswer(i->i.getArgument(0));when(refresh.save(any())).thenAnswer(i->{CustomerRefreshToken t=i.getArgument(0);if(t.getId()==null)ReflectionTestUtils.setField(t,"id",ids.getAndIncrement());return t;});when(resets.save(any())).thenAnswer(i->i.getArgument(0));when(otps.findByAccountIdAndPurposeAndConsumedAtIsNull(anyLong(),any())).thenReturn(List.of());when(jwt.issue(anyLong())).thenReturn(new CustomerJwtService.IssuedAccess("access",Instant.now().plusSeconds(900)));doAnswer(i->{deliveredOtp=i.getArgument(2);return null;}).when(mail).registrationOtp(any(),anyString(),anyString(),anyLong());doAnswer(i->{deliveredOtp=i.getArgument(2);return null;}).when(mail).passwordResetOtp(any(),anyString(),anyString(),anyLong());}
 @AfterEach void close()throws Exception{mocks.close();}
 private RegisterRequest request(){return new RegisterRequest("Test Customer","Customer@Example.com","+880 1712-345678","Strong1!","Strong1!",true);}
 private CustomerAccount register(){when(accounts.findByEmailIgnoreCase("customer@example.com")).thenReturn(Optional.empty());when(customers.findByEmailIgnoreCase("customer@example.com")).thenReturn(List.of());service.register(request());ArgumentCaptor<CustomerAccount> cap=ArgumentCaptor.forClass(CustomerAccount.class);verify(accounts,atLeastOnce()).save(cap.capture());return cap.getValue();}
 @Test void registrationCreatesPendingCustomerAndHashesSecrets(){CustomerAccount a=register();assertEquals("customer@example.com",a.getEmail());assertEquals("01712345678",a.getCustomer().getPhone());assertEquals(CustomerAccount.Status.PENDING_VERIFICATION,a.getStatus());assertTrue(encoder.matches("Strong1!",a.getPasswordHash()));ArgumentCaptor<CustomerAuthOtp> cap=ArgumentCaptor.forClass(CustomerAuthOtp.class);verify(otps).save(cap.capture());assertNotEquals(deliveredOtp,cap.getValue().getOtpHash());assertTrue(encoder.matches(deliveredOtp,cap.getValue().getOtpHash()));verify(mail).registrationOtp(eq(a),eq("Test Customer"),anyString(),eq(10L));}
 @Test void duplicateActiveEmailIsRejected(){CustomerAccount a=active();when(accounts.findByEmailIgnoreCase("customer@example.com")).thenReturn(Optional.of(a));CustomerAuthException e=assertThrows(CustomerAuthException.class,()->service.register(request()));assertEquals("EMAIL_ALREADY_REGISTERED",e.code());}
 @Test void ambiguousExistingCustomerRequiresReview(){when(accounts.findByEmailIgnoreCase(anyString())).thenReturn(Optional.empty());when(customers.findByEmailIgnoreCase(anyString())).thenReturn(List.of(customer(1),customer(2)));assertEquals("CUSTOMER_LINK_REVIEW_REQUIRED",assertThrows(CustomerAuthException.class,()->service.register(request())).code());}
 @Test void validRegistrationOtpActivatesAndIssuesOnlyCustomerSession(){CustomerAccount a=pending();CustomerAuthOtp o=otp(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY,"123456");when(accounts.findByEmailIgnoreCase(a.getEmail())).thenReturn(Optional.of(a));when(otps.findTopByAccountIdAndPurposeOrderByCreatedAtDesc(a.getId(),o.getPurpose())).thenReturn(Optional.of(o));AuthResponse result=service.verifyRegistration(new EmailOtpRequest(a.getEmail(),"123456"));assertEquals(CustomerAccount.Status.ACTIVE,a.getStatus());assertTrue(a.isEmailVerified());assertEquals("access",result.accessToken());assertEquals(a.getCustomer().getCustomerId(),result.profile().customerId());}
 @Test void invalidOtpIncrementsAttemptsWithoutLeakingHash(){CustomerAccount a=pending();CustomerAuthOtp o=otp(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY,"123456");when(accounts.findByEmailIgnoreCase(a.getEmail())).thenReturn(Optional.of(a));when(otps.findTopByAccountIdAndPurposeOrderByCreatedAtDesc(a.getId(),o.getPurpose())).thenReturn(Optional.of(o));assertEquals("OTP_INVALID",assertThrows(CustomerAuthException.class,()->service.verifyRegistration(new EmailOtpRequest(a.getEmail(),"000000"))).code());assertEquals(1,o.getAttempts());}
 @Test void pendingAccountCannotLogin(){CustomerAccount a=pending();when(accounts.findByEmailIgnoreCase(a.getEmail())).thenReturn(Optional.of(a));assertEquals("ACCOUNT_PENDING_VERIFICATION",assertThrows(CustomerAuthException.class,()->service.login(new LoginRequest(a.getEmail(),"Strong1!",null))).code());}
 @Test void unknownAndWrongPasswordUseSameGenericCode(){when(accounts.findByEmailIgnoreCase("none@example.com")).thenReturn(Optional.empty());assertEquals("INVALID_CREDENTIALS",assertThrows(CustomerAuthException.class,()->service.login(new LoginRequest("none@example.com","Wrong1!",null))).code());CustomerAccount a=active();when(accounts.findByEmailIgnoreCase(a.getEmail())).thenReturn(Optional.of(a));assertEquals("INVALID_CREDENTIALS",assertThrows(CustomerAuthException.class,()->service.login(new LoginRequest(a.getEmail(),"Wrong1!",null))).code());}
 @Test void repeatedLoginFailureLocksAccount(){CustomerAccount a=active();when(accounts.findByEmailIgnoreCase(a.getEmail())).thenReturn(Optional.of(a));for(int i=0;i<5;i++)assertThrows(CustomerAuthException.class,()->service.login(new LoginRequest(a.getEmail(),"Wrong1!",null)));assertEquals(CustomerAccount.Status.LOCKED,a.getStatus());assertNotNull(a.getLockedUntil());}
 @Test void successfulLoginResetsCounterAndReturnsRedactedToString(){CustomerAccount a=active();a.setFailedLoginAttempts(3);when(accounts.findByEmailIgnoreCase(a.getEmail())).thenReturn(Optional.of(a));AuthResponse r=service.login(new LoginRequest(a.getEmail(),"Strong1!","Samsung"));assertEquals(0,a.getFailedLoginAttempts());assertFalse(r.toString().contains(r.accessToken()));assertFalse(r.toString().contains(r.refreshToken()));}
 @Test void refreshRotatesAndRevokesUsedToken(){CustomerAccount a=active();CustomerRefreshToken old=token(a,null);when(refresh.findByTokenHash(anyString())).thenReturn(Optional.of(old));TokenResponse r=service.refresh(new RefreshRequest("old-raw-token","Samsung"));assertNotNull(old.getRevokedAt());assertNotNull(old.getReplacedByTokenId());assertFalse(r.toString().contains(r.refreshToken()));}
 @Test void reusedRefreshRevokesWholeFamily(){CustomerAccount a=active();CustomerRefreshToken old=token(a,Instant.now());CustomerRefreshToken sibling=token(a,null);when(refresh.findByTokenHash(anyString())).thenReturn(Optional.of(old));when(refresh.findByTokenFamilyIdAndRevokedAtIsNull("family")).thenReturn(List.of(sibling));assertEquals("SESSION_REVOKED",assertThrows(CustomerAuthException.class,()->service.refresh(new RefreshRequest("reused",null))).code());assertNotNull(sibling.getRevokedAt());}
 @Test void forgotPasswordIsEnumerationSafe(){when(accounts.findByEmailIgnoreCase("missing@example.com")).thenReturn(Optional.empty());MessageResponse r=service.forgotPassword(new EmailRequest("missing@example.com"));assertEquals("If an eligible account exists, a verification code has been sent.",r.message());verifyNoInteractions(mail);}
 @Test void profileExcludesFinancialAndSecurityInternals(){CustomerAccount a=active();when(accounts.findById(a.getId())).thenReturn(Optional.of(a));CustomerProfileResponse p=service.profile(a.getId());assertEquals(a.getEmail(),p.email());assertFalse(p.toString().contains("password"));assertFalse(p.toString().contains("balance"));assertFalse(p.toString().contains("role"));}
 @Test void changePasswordRevokesSessionsAndRequiresCurrentPassword(){CustomerAccount a=active();when(accounts.findById(a.getId())).thenReturn(Optional.of(a));assertEquals("CURRENT_PASSWORD_INCORRECT",assertThrows(CustomerAuthException.class,()->service.changePassword(a.getId(),new ChangePasswordRequest("bad","OtherPass2@","OtherPass2@"))).code());CustomerRefreshToken t=token(a,null);when(refresh.findByAccountIdAndRevokedAtIsNull(a.getId())).thenReturn(List.of(t));service.changePassword(a.getId(),new ChangePasswordRequest("Strong1!","OtherPass2@","OtherPass2@"));assertTrue(encoder.matches("OtherPass2@",a.getPasswordHash()));assertNotNull(t.getRevokedAt());verify(mail).passwordChanged(a,"Test Customer");}
 private Customer customer(long id){Customer c=new Customer();c.setCustomerId(id);c.setCustomerCode("C"+id);c.setCustomerName("Test Customer");c.setEmail("customer@example.com");c.setPhone("01712345678");c.setCustomerType(Customer.CustomerType.RETAIL);c.setStatus(true);return c;}
 private CustomerAccount pending(){CustomerAccount a=new CustomerAccount();a.setId(10L);a.setCustomer(customer(20));a.setEmail("customer@example.com");a.setPasswordHash(encoder.encode("Strong1!"));a.setStatus(CustomerAccount.Status.PENDING_VERIFICATION);return a;}
 private CustomerAccount active(){CustomerAccount a=pending();a.setStatus(CustomerAccount.Status.ACTIVE);a.setEmailVerified(true);return a;}
 private CustomerAuthOtp otp(CustomerAccount a,CustomerAuthOtp.Purpose p,String raw){CustomerAuthOtp o=new CustomerAuthOtp();o.setAccount(a);o.setPurpose(p);o.setOtpHash(encoder.encode(raw));o.setExpiresAt(Instant.now().plusSeconds(600));o.setLastSentAt(Instant.now().minusSeconds(60));o.setMaxAttempts(5);return o;}
 private CustomerRefreshToken token(CustomerAccount a,Instant revoked){CustomerRefreshToken t=new CustomerRefreshToken();ReflectionTestUtils.setField(t,"id",ids.getAndIncrement());t.setAccount(a);t.setTokenHash("stored-hash");t.setTokenFamilyId("family");t.setIssuedAt(Instant.now());t.setExpiresAt(Instant.now().plusSeconds(3600));t.setRevokedAt(revoked);return t;}
}
