package com.trademaster.ims.mobile.fulfillment;

import com.trademaster.ims.config.SecurityConfig;import com.trademaster.ims.mobile.auth.security.*;import com.trademaster.ims.mobile.common.exception.MobileExceptionHandler;import com.trademaster.ims.mobile.fulfillment.controller.*;import com.trademaster.ims.mobile.fulfillment.dto.FulfillmentDtos.*;import com.trademaster.ims.mobile.fulfillment.service.OrderFulfillmentService;import com.trademaster.ims.security.*;import jakarta.servlet.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;import org.springframework.context.annotation.*;import org.springframework.test.context.ContextConfiguration;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;import java.time.*;import java.util.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(controllers={OrderFulfillmentController.class,MobileOrderTrackingController.class})@Import({SecurityConfig.class,MobileExceptionHandler.class})@ContextConfiguration(classes={OrderFulfillmentController.class,MobileOrderTrackingController.class,SecurityConfig.class,MobileExceptionHandler.class})class OrderFulfillmentSecurityTest{@Autowired MockMvc mvc;@MockitoBean OrderFulfillmentService service;@MockitoBean UserDetailsServiceImpl users;@MockitoBean JwtUtils jwt;@MockitoBean CustomerAuthTokenFilter filter;
 @BeforeEach void setup()throws Exception{doAnswer(i->{((FilterChain)i.getArgument(2)).doFilter((ServletRequest)i.getArgument(0),(ServletResponse)i.getArgument(1));return null;}).when(filter).doFilter(any(),any(),any());when(service.adminDetail("TSS-1")).thenReturn(new FulfillmentDetail("TSS-1","FUL-1","CONFIRMED","PAID","POSTED","PROCESSING",false,1L,null,null,null,null,null,null,null,null,List.of(),List.of()));when(service.customerTracking(7L,"TSS-1")).thenReturn(new OrderTrackingResponse("TSS-1","CONFIRMED","PROCESSING","PAID",null,"Home",LocalDate.now(),null,null,null,null,"PROCESSING",List.of(new TrackingStep("PROCESSING","Processing","Preparing","CURRENT",Instant.now())),List.of()));}
 @Test void anonymousDeniedFromAdminFulfillment()throws Exception{mvc.perform(get("/api/orders/fulfillment/TSS-1")).andExpect(status().isUnauthorized());}
 @Test void customerDeniedFromAdminFulfillment()throws Exception{mvc.perform(get("/api/orders/fulfillment/TSS-1").with(authentication(new CustomerAuthentication(7L)))).andExpect(status().isForbidden());}
 @Test void adminCanReadFulfillmentDetail()throws Exception{mvc.perform(get("/api/orders/fulfillment/TSS-1").with(user("admin").roles("ADMIN"))).andExpect(status().isOk()).andExpect(jsonPath("$.fulfillmentNumber").value("FUL-1"));}
 @Test void customerTrackingUsesCustomerPrincipal()throws Exception{mvc.perform(get("/api/mobile/v1/orders/TSS-1/tracking").with(authentication(new CustomerAuthentication(7L)))).andExpect(status().isOk()).andExpect(jsonPath("$.orderNumber").value("TSS-1"));verify(service).customerTracking(7L,"TSS-1");}
 @Test void employeeDeniedFromCustomerTracking()throws Exception{mvc.perform(get("/api/mobile/v1/orders/TSS-1/tracking").with(user("employee").roles("EMPLOYEE"))).andExpect(status().isForbidden());}
}