package com.trademaster.ims.mobile.notifications.service;

import com.trademaster.ims.mobile.auth.model.CustomerAccount;
import com.trademaster.ims.mobile.auth.repository.CustomerAccountRepository;
import com.trademaster.ims.mobile.auth.service.CustomerAuthException;
import com.trademaster.ims.mobile.notifications.dto.NotificationDtos.*;
import com.trademaster.ims.mobile.notifications.model.*;
import com.trademaster.ims.mobile.notifications.repository.*;
import jakarta.persistence.criteria.Predicate;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@Service @Transactional
public class CustomerNotificationService{
 private final CustomerNotificationRepository notifications; private final NotificationTemplateRepository templates; private final CustomerNotificationPreferenceRepository preferences; private final CustomerAccountRepository accounts; private final CustomerNotificationEmailService email;
 public CustomerNotificationService(CustomerNotificationRepository n,NotificationTemplateRepository t,CustomerNotificationPreferenceRepository p,CustomerAccountRepository a,CustomerNotificationEmailService e){notifications=n;templates=t;preferences=p;accounts=a;email=e;}
 public CustomerNotification orderCreated(long account,String orderNumber,BigDecimal amount,String currency){return create(account,CustomerNotification.NotificationType.ORDER_CREATED,vars("orderNumber",orderNumber,"amount",money(amount),"currency",currency),"ORDER",orderNumber,CustomerNotification.ActionType.OPEN_ORDER,orderNumber,"ORDER_CREATED:"+orderNumber,false);}
 public CustomerNotification orderConfirmed(long account,String orderNumber){return create(account,CustomerNotification.NotificationType.ORDER_CONFIRMED,vars("orderNumber",orderNumber),"ORDER",orderNumber,CustomerNotification.ActionType.OPEN_ORDER,orderNumber,"ORDER_CONFIRMED:"+orderNumber,false);}
 public CustomerNotification cancellationRequested(long account,String orderNumber){return create(account,CustomerNotification.NotificationType.ORDER_CANCEL_REQUESTED,vars("orderNumber",orderNumber),"CANCELLATION",orderNumber,CustomerNotification.ActionType.OPEN_CANCELLATION_REQUEST,orderNumber,"CANCELLATION_REQUESTED:"+orderNumber,false);}
 public CustomerNotification returnRequested(long account,String orderNumber,String requestNumber){return create(account,CustomerNotification.NotificationType.RETURN_REQUESTED,vars("orderNumber",orderNumber,"returnRequestNumber",requestNumber),"RETURN",requestNumber,CustomerNotification.ActionType.OPEN_RETURN_REQUEST,orderNumber,"RETURN_REQUESTED:"+requestNumber,false);}
 public CustomerNotification paymentInitiated(long account,String orderNumber,String paymentNumber,BigDecimal amount,String method){return create(account,CustomerNotification.NotificationType.PAYMENT_INITIATED,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"amount",money(amount),"method",method),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"PAYMENT_INITIATED:"+paymentNumber,false);}
 public CustomerNotification manualSubmitted(long account,String orderNumber,String paymentNumber,BigDecimal amount,String method){create(account,CustomerNotification.NotificationType.PAYMENT_REVIEW_REQUIRED,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"amount",money(amount),"method",method),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"PAYMENT_REVIEW_REQUIRED:"+paymentNumber,false);return create(account,CustomerNotification.NotificationType.MANUAL_PAYMENT_SUBMITTED,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"amount",money(amount),"method",method),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"MANUAL_PAYMENT_SUBMITTED:"+paymentNumber,false);}
 public CustomerNotification codPending(long account,String orderNumber,String paymentNumber,BigDecimal amount){return create(account,CustomerNotification.NotificationType.COD_PENDING,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"amount",money(amount),"method","Cash on Delivery"),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"COD_PENDING:"+paymentNumber,false);}
 public CustomerNotification paymentPaid(long account,String orderNumber,String paymentNumber,BigDecimal amount,String method){CustomerNotification n=create(account,CustomerNotification.NotificationType.PAYMENT_PAID,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"amount",money(amount),"method",method),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"PAYMENT_PAID:"+paymentNumber,true);orderConfirmed(account,orderNumber);return n;}
 public CustomerNotification walletSuccess(long account,String orderNumber,String paymentNumber,BigDecimal amount,String provider){create(account,CustomerNotification.NotificationType.WALLET_PAYMENT_SUCCESS,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"amount",money(amount),"provider",provider),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"WALLET_PAYMENT_SUCCESS:"+paymentNumber,true);return paymentPaid(account,orderNumber,paymentNumber,amount,provider);}
 public CustomerNotification paymentFailed(long account,String orderNumber,String paymentNumber,String method){return create(account,CustomerNotification.NotificationType.PAYMENT_FAILED,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber,"method",method),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"PAYMENT_FAILED:"+paymentNumber+":"+Instant.now().getEpochSecond(),false);}
 public CustomerNotification paymentRejected(long account,String orderNumber,String paymentNumber){return create(account,CustomerNotification.NotificationType.PAYMENT_REJECTED,vars("orderNumber",orderNumber,"paymentNumber",paymentNumber),"PAYMENT",paymentNumber,CustomerNotification.ActionType.OPEN_PAYMENT,orderNumber,"PAYMENT_REJECTED:"+paymentNumber,false);}
 public CustomerNotification profileUpdated(long account){return create(account,CustomerNotification.NotificationType.SYSTEM_MESSAGE,vars(),"ACCOUNT","PROFILE",CustomerNotification.ActionType.OPEN_PROFILE,"PROFILE","PROFILE_UPDATED:"+account+":"+LocalDate.now(),false);}
 public CustomerNotification passwordChanged(long account){return create(account,CustomerNotification.NotificationType.SECURITY_ALERT,vars(),"ACCOUNT","PASSWORD",CustomerNotification.ActionType.OPEN_PROFILE,"PROFILE","PASSWORD_CHANGED:"+account+":"+Instant.now().getEpochSecond(),true);}
 public CustomerNotification create(long account,CustomerNotification.NotificationType type,Map<String,String> variables,String relatedType,String relatedRef,CustomerNotification.ActionType action,String actionRef,String eventKey,boolean critical){seedTemplates();if(eventKey!=null&&notifications.existsByEventKey(eventKey))return notifications.findByEventKey(eventKey).orElse(null);CustomerAccount customer=accounts.findById(account).orElse(null);if(customer==null)return null;NotificationTemplate template=templates.findByCodeAndLocaleAndActiveTrue(type.name(),"en").orElseThrow();CustomerNotificationPreference pref=preference(customer,template.getCategory());boolean inApp=critical||pref.isInAppEnabled();boolean emailEnabled=critical||pref.isEmailEnabled();if(!inApp&&!emailEnabled)return null;CustomerNotification n=new CustomerNotification();n.setCustomer(customer);n.setNotificationNumber(number());n.setEventKey(eventKey==null?type+":"+account+":"+UUID.randomUUID():eventKey);n.setType(type);n.setCategory(template.getCategory());n.setSeverity(template.getSeverity());n.setChannel(template.getDefaultChannel());n.setTitle(render(template.getTitleTemplate(),variables));n.setMessage(render(template.getMessageTemplate(),variables));n.setShortMessage(render(template.getShortMessageTemplate(),variables));n.setRelatedEntityType(relatedType);n.setRelatedEntityReference(relatedRef);n.setActionType(action==null?CustomerNotification.ActionType.NONE:action);n.setActionReference(actionRef);n.setDeliveryStatus(inApp?CustomerNotification.DeliveryStatus.IN_APP_DELIVERED:CustomerNotification.DeliveryStatus.SUPPRESSED_BY_PREFERENCE);try{n=notifications.saveAndFlush(n);}catch(DataIntegrityViolationException ex){return eventKey==null?null:notifications.findByEventKey(eventKey).orElse(null);}if(emailEnabled&&(n.getChannel()==CustomerNotification.Channel.EMAIL||n.getChannel()==CustomerNotification.Channel.BOTH)){n.setDeliveryStatus(email.send(customer,n));n=notifications.save(n);}return n;}
 @Transactional(readOnly=true) public NotificationPage list(long account,int page,int size,String category,String readStatus){int s=Math.max(1,Math.min(size<=0?20:size,50));Pageable pageable=PageRequest.of(Math.max(0,page),s,Sort.by("createdAt").descending());CustomerNotification.Category c=parseCategory(category,false);CustomerNotification.ReadStatus r=parseRead(readStatus);Specification<CustomerNotification> spec=(root,q,cb)->{List<Predicate> ps=new ArrayList<>();ps.add(cb.equal(root.get("customer").get("id"),account));ps.add(cb.or(cb.isNull(root.get("expiresAt")),cb.greaterThan(root.get("expiresAt"),Instant.now())));if(c!=null)ps.add(cb.equal(root.get("category"),c));if(r!=null)ps.add(cb.equal(root.get("readStatus"),r));return cb.and(ps.toArray(Predicate[]::new));};Page<CustomerNotification> pg=notifications.findAll(spec,pageable);return new NotificationPage(pg.getContent().stream().map(this::summary).toList(),pg.getNumber(),pg.getSize(),pg.getTotalElements(),pg.getTotalPages(),pg.isFirst(),pg.isLast());}
 @Transactional(readOnly=true) public UnreadCountResponse unread(long account){return new UnreadCountResponse(notifications.unreadCount(account,Instant.now()));}
 @Transactional(readOnly=true) public NotificationDetail detail(long account,String number){return detailDto(owned(account,number));}
 public NotificationDetail markRead(long account,String number){CustomerNotification n=owned(account,number);if(n.getReadStatus()!=CustomerNotification.ReadStatus.READ){n.setReadStatus(CustomerNotification.ReadStatus.READ);n.setReadAt(Instant.now());notifications.save(n);}return detailDto(n);}
 public UnreadCountResponse markAllRead(long account){notifications.markAllRead(account,Instant.now());return unread(account);}
 public List<NotificationPreferenceResponse> getPreferences(long account){CustomerAccount c=accounts.findById(account).orElseThrow(()->err(HttpStatus.UNAUTHORIZED,"AUTHENTICATION_REQUIRED","Authentication is required."));ensurePreferences(c);return preferences.findByAccount(account).stream().map(this::prefDto).toList();}
 public List<NotificationPreferenceResponse> updatePreferences(long account,PreferenceUpdateRequest request){CustomerAccount c=accounts.findById(account).orElseThrow(()->err(HttpStatus.UNAUTHORIZED,"AUTHENTICATION_REQUIRED","Authentication is required."));ensurePreferences(c);if(request!=null&&request.preferences()!=null){for(PreferenceUpdateItem item:request.preferences()){CustomerNotification.Category cat=parseCategory(item.category(),true);CustomerNotificationPreference p=preference(c,cat);if(!critical(cat)){if(item.inAppEnabled()!=null)p.setInAppEnabled(item.inAppEnabled());if(item.emailEnabled()!=null)p.setEmailEnabled(item.emailEnabled());}else{p.setInAppEnabled(true);if(item.emailEnabled()!=null)p.setEmailEnabled(item.emailEnabled());}preferences.save(p);}}return getPreferences(account);} private CustomerNotification owned(long account,String number){return notifications.findOwned(account,number).orElseThrow(()->err(HttpStatus.NOT_FOUND,"NOTIFICATION_NOT_FOUND","Notification not found."));}
 private NotificationSummary summary(CustomerNotification n){return new NotificationSummary(n.getNotificationNumber(),n.getType().name(),n.getCategory().name(),n.getTitle(),n.getShortMessage(),n.getSeverity().name(),n.getReadStatus()==CustomerNotification.ReadStatus.READ,n.getCreatedAt(),n.getRelatedEntityType(),n.getRelatedEntityReference(),n.getActionType().name());}
 private NotificationDetail detailDto(CustomerNotification n){return new NotificationDetail(n.getNotificationNumber(),n.getType().name(),n.getCategory().name(),n.getTitle(),n.getMessage(),n.getSeverity().name(),n.getReadStatus()==CustomerNotification.ReadStatus.READ,n.getCreatedAt(),n.getReadAt(),n.getRelatedEntityType(),n.getRelatedEntityReference(),n.getActionType().name(),n.getActionReference());}
 private NotificationPreferenceResponse prefDto(CustomerNotificationPreference p){return new NotificationPreferenceResponse(p.getCategory().name(),p.isInAppEnabled(),p.isEmailEnabled(),critical(p.getCategory()));}
 private void ensurePreferences(CustomerAccount c){for(CustomerNotification.Category cat:CustomerNotification.Category.values())preference(c,cat);}
 private CustomerNotificationPreference preference(CustomerAccount c,CustomerNotification.Category cat){return preferences.findByAccountAndCategory(c.getId(),cat).orElseGet(()->{CustomerNotificationPreference p=new CustomerNotificationPreference();p.setCustomer(c);p.setCategory(cat);p.setInAppEnabled(true);p.setEmailEnabled(cat==CustomerNotification.Category.ORDER||cat==CustomerNotification.Category.PAYMENT||cat==CustomerNotification.Category.ACCOUNT);return preferences.save(p);});}
 private boolean critical(CustomerNotification.Category c){return c==CustomerNotification.Category.ACCOUNT;}
 private CustomerNotification.Category parseCategory(String v,boolean required){if(!StringUtils.hasText(v)){if(required)throw err(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Category is required.");return null;}try{return CustomerNotification.Category.valueOf(v.trim().toUpperCase(Locale.ROOT));}catch(Exception e){throw err(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Unsupported notification category.");}}
 private CustomerNotification.ReadStatus parseRead(String v){if(!StringUtils.hasText(v)||"all".equalsIgnoreCase(v))return null;if("unread".equalsIgnoreCase(v))return CustomerNotification.ReadStatus.UNREAD;if("read".equalsIgnoreCase(v))return CustomerNotification.ReadStatus.READ;throw err(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Unsupported read status filter.");}
 private void seedTemplates(){for(DefaultTemplate d:defaults())if(!templates.existsByCodeAndLocale(d.type.name(),"en")){NotificationTemplate t=new NotificationTemplate();t.setCode(d.type.name());t.setTitleTemplate(d.title);t.setMessageTemplate(d.message);t.setShortMessageTemplate(d.shortMessage);t.setCategory(d.category);t.setSeverity(d.severity);t.setDefaultChannel(d.channel);t.setLocale("en");templates.save(t);}}
 private List<DefaultTemplate> defaults(){return List.of(
  d(CustomerNotification.NotificationType.ORDER_CREATED,CustomerNotification.Category.ORDER,CustomerNotification.Severity.INFO,"Order {orderNumber} received","Your order {orderNumber} for {currency} {amount} was received and is awaiting confirmation.","Order {orderNumber} received"),
  d(CustomerNotification.NotificationType.ORDER_CONFIRMED,CustomerNotification.Category.ORDER,CustomerNotification.Severity.SUCCESS,"Order {orderNumber} confirmed","Your order {orderNumber} is confirmed.","Order {orderNumber} confirmed"),
  d(CustomerNotification.NotificationType.ORDER_PROCESSING,CustomerNotification.Category.ORDER,CustomerNotification.Severity.INFO,"Order {orderNumber} is processing","Your order {orderNumber} is being prepared by our team.","Order processing"),
  d(CustomerNotification.NotificationType.ORDER_PACKED,CustomerNotification.Category.ORDER,CustomerNotification.Severity.INFO,"Order {orderNumber} packed","Your order {orderNumber} has been packed and is ready to ship.","Order packed"),
  d(CustomerNotification.NotificationType.ORDER_SHIPPED,CustomerNotification.Category.ORDER,CustomerNotification.Severity.INFO,"Order {orderNumber} shipped","Your order {orderNumber} has been shipped. Tracking information is available when provided.","Order shipped"),
  d(CustomerNotification.NotificationType.ORDER_OUT_FOR_DELIVERY,CustomerNotification.Category.ORDER,CustomerNotification.Severity.INFO,"Order {orderNumber} is out for delivery","Your order {orderNumber} is out for delivery.","Out for delivery"),
  d(CustomerNotification.NotificationType.ORDER_DELIVERED,CustomerNotification.Category.ORDER,CustomerNotification.Severity.SUCCESS,"Order {orderNumber} delivered","Your order {orderNumber} has been delivered.","Order delivered"),
  d(CustomerNotification.NotificationType.ORDER_CANCEL_REQUESTED,CustomerNotification.Category.CANCELLATION,CustomerNotification.Severity.WARNING,"Cancellation requested","Your cancellation request for order {orderNumber} was received for review.","Cancellation requested for {orderNumber}"),
  d(CustomerNotification.NotificationType.RETURN_REQUESTED,CustomerNotification.Category.RETURN,CustomerNotification.Severity.WARNING,"Return requested","Your return request {returnRequestNumber} for order {orderNumber} was received for review.","Return request received"),
  d(CustomerNotification.NotificationType.PAYMENT_INITIATED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.INFO,"Payment started","Payment {paymentNumber} for order {orderNumber} was started using {method}.","Payment started for {orderNumber}"),
  d(CustomerNotification.NotificationType.PAYMENT_PAID,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.SUCCESS,"Payment successful","Payment {paymentNumber} for {amount} was received for order {orderNumber}.","Payment successful"),
  d(CustomerNotification.NotificationType.PAYMENT_FAILED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.ERROR,"Payment failed","Payment {paymentNumber} for order {orderNumber} failed. You may retry from the app.","Payment failed"),
  d(CustomerNotification.NotificationType.PAYMENT_REVIEW_REQUIRED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.WARNING,"Payment under review","Payment {paymentNumber} for order {orderNumber} requires review.","Payment under review"),
  d(CustomerNotification.NotificationType.PAYMENT_REJECTED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.ERROR,"Payment rejected","Payment {paymentNumber} for order {orderNumber} was rejected.","Payment rejected"),
  d(CustomerNotification.NotificationType.COD_PENDING,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.INFO,"Cash on Delivery selected","Cash on Delivery is pending for order {orderNumber}.","COD pending"),
  d(CustomerNotification.NotificationType.COD_PAYMENT_COLLECTED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.SUCCESS,"COD collected","Cash on Delivery payment {paymentNumber} for order {orderNumber} was collected.","COD collected"),
  d(CustomerNotification.NotificationType.COD_PAYMENT_RECONCILED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.SUCCESS,"COD reconciled","Cash on Delivery payment {paymentNumber} for order {orderNumber} was reconciled.","COD reconciled"),
  d(CustomerNotification.NotificationType.WALLET_PAYMENT_SUCCESS,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.SUCCESS,"Wallet payment successful","{provider} wallet payment {paymentNumber} succeeded for order {orderNumber}.","Wallet payment successful"),
  d(CustomerNotification.NotificationType.MANUAL_PAYMENT_SUBMITTED,CustomerNotification.Category.PAYMENT,CustomerNotification.Severity.WARNING,"Manual payment submitted","Manual payment {paymentNumber} for order {orderNumber} was submitted for review.","Manual payment submitted"),
  d(CustomerNotification.NotificationType.SYSTEM_MESSAGE,CustomerNotification.Category.ACCOUNT,CustomerNotification.Severity.INFO,"Profile updated","Your TechSmart Shop profile was updated.","Profile updated"),
  d(CustomerNotification.NotificationType.SECURITY_ALERT,CustomerNotification.Category.ACCOUNT,CustomerNotification.Severity.WARNING,"Security alert","Your TechSmart Shop password was changed. If this was not you, contact support.","Password changed"),
  d(CustomerNotification.NotificationType.ORDER_CANCEL_APPROVED,CustomerNotification.Category.CANCELLATION,CustomerNotification.Severity.SUCCESS,"Cancellation approved","Your cancellation request for order {orderNumber} was approved.","Cancellation approved"),
  d(CustomerNotification.NotificationType.ORDER_CANCEL_REJECTED,CustomerNotification.Category.CANCELLATION,CustomerNotification.Severity.ERROR,"Cancellation rejected","Your cancellation request for order {orderNumber} was rejected.","Cancellation rejected"),
  d(CustomerNotification.NotificationType.RETURN_APPROVED,CustomerNotification.Category.RETURN,CustomerNotification.Severity.SUCCESS,"Return approved","Your return request {returnRequestNumber} was approved.","Return approved"),
  d(CustomerNotification.NotificationType.RETURN_REJECTED,CustomerNotification.Category.RETURN,CustomerNotification.Severity.ERROR,"Return rejected","Your return request {returnRequestNumber} was rejected.","Return rejected")
 );}
 private DefaultTemplate d(CustomerNotification.NotificationType t,CustomerNotification.Category c,CustomerNotification.Severity s,String title,String msg,String shortMsg){return new DefaultTemplate(t,c,s,CustomerNotification.Channel.BOTH,title,msg,shortMsg);} private record DefaultTemplate(CustomerNotification.NotificationType type,CustomerNotification.Category category,CustomerNotification.Severity severity,CustomerNotification.Channel channel,String title,String message,String shortMessage){}
 private String render(String template,Map<String,String> vars){String out=template;for(Map.Entry<String,String> e:vars.entrySet())out=out.replace("{"+e.getKey()+"}",e.getValue()==null?"":e.getValue());return out.replaceAll("\\{[A-Za-z0-9_]+\\}","").replaceAll(" +"," ").trim();}
 private Map<String,String> vars(Object... pairs){Map<String,String> m=new HashMap<>();for(int i=0;i+1<pairs.length;i+=2)m.put(String.valueOf(pairs[i]),pairs[i+1]==null?"":String.valueOf(pairs[i+1]));return m;}
 private String money(BigDecimal v){return v==null?"0.00":v.setScale(2,java.math.RoundingMode.HALF_UP).toPlainString();}
 private String number(){String n;do{n="NTF-"+LocalDate.now().toString().replace("-","")+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT);}while(notifications.existsByNotificationNumber(n));return n;}
 private CustomerAuthException err(HttpStatus s,String c,String m){return new CustomerAuthException(s,c,m);} }