package com.trademaster.ims.mobile.fulfillment.model;

import com.trademaster.ims.mobile.checkout.model.CustomerOrder;
import jakarta.persistence.*;import java.time.*;
@Entity @Table(name="order_fulfillments",uniqueConstraints={@UniqueConstraint(name="uk_order_fulfillment_number",columnNames="fulfillment_number"),@UniqueConstraint(name="uk_order_fulfillment_order",columnNames="order_id")},indexes={@Index(name="idx_order_fulfillment_status",columnList="status"),@Index(name="idx_order_fulfillment_tracking",columnList="tracking_number")})
public class OrderFulfillment{
 public enum FulfillmentStatus{PROCESSING,PACKED,SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED,DELIVERY_EXCEPTION}
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;
 @Column(name="fulfillment_number",nullable=false,length=48)private String fulfillmentNumber;
 @OneToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="order_id",nullable=false)private CustomerOrder order;
 @Column(name="order_number",nullable=false,length=50)private String orderNumber;
 @Column(name="warehouse_id")private Long warehouseId;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=32)private FulfillmentStatus status=FulfillmentStatus.PROCESSING;
 @Column(name="stock_deducted",nullable=false)private boolean stockDeducted=false;
 @Column(name="stock_deducted_at")private Instant stockDeductedAt;
 @Column(name="stock_movement_reference",length=120)private String stockMovementReference;
 @Column(name="packed_at")private Instant packedAt;@Column(name="shipped_at")private Instant shippedAt;@Column(name="out_for_delivery_at")private Instant outForDeliveryAt;@Column(name="delivered_at")private Instant deliveredAt;
 @Column(name="delivery_partner",length=120)private String deliveryPartner;@Column(name="tracking_number",length=120)private String trackingNumber;
 @Column(name="delivery_contact_name",length=120)private String deliveryContactName;@Column(name="delivery_contact_phone",length=30)private String deliveryContactPhone;
 @Column(name="estimated_delivery_date")private LocalDate estimatedDeliveryDate;@Column(name="actual_delivery_date")private LocalDate actualDeliveryDate;
 @Column(name="delivery_note",length=700)private String deliveryNote;@Column(name="created_by",length=120)private String createdBy;@Column(name="updated_by",length=120)private String updatedBy;
 @Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Version private Long version;
 @PrePersist void p(){Instant n=Instant.now();createdAt=n;updatedAt=n;}@PreUpdate void u(){updatedAt=Instant.now();}
 public Long getId(){return id;}public String getFulfillmentNumber(){return fulfillmentNumber;}public void setFulfillmentNumber(String v){fulfillmentNumber=v;}public CustomerOrder getOrder(){return order;}public void setOrder(CustomerOrder v){order=v;}public String getOrderNumber(){return orderNumber;}public void setOrderNumber(String v){orderNumber=v;}public Long getWarehouseId(){return warehouseId;}public void setWarehouseId(Long v){warehouseId=v;}public FulfillmentStatus getStatus(){return status;}public void setStatus(FulfillmentStatus v){status=v;}public boolean isStockDeducted(){return stockDeducted;}public void setStockDeducted(boolean v){stockDeducted=v;}public Instant getStockDeductedAt(){return stockDeductedAt;}public void setStockDeductedAt(Instant v){stockDeductedAt=v;}public String getStockMovementReference(){return stockMovementReference;}public void setStockMovementReference(String v){stockMovementReference=v;}public Instant getPackedAt(){return packedAt;}public void setPackedAt(Instant v){packedAt=v;}public Instant getShippedAt(){return shippedAt;}public void setShippedAt(Instant v){shippedAt=v;}public Instant getOutForDeliveryAt(){return outForDeliveryAt;}public void setOutForDeliveryAt(Instant v){outForDeliveryAt=v;}public Instant getDeliveredAt(){return deliveredAt;}public void setDeliveredAt(Instant v){deliveredAt=v;}public String getDeliveryPartner(){return deliveryPartner;}public void setDeliveryPartner(String v){deliveryPartner=v;}public String getTrackingNumber(){return trackingNumber;}public void setTrackingNumber(String v){trackingNumber=v;}public String getDeliveryContactName(){return deliveryContactName;}public void setDeliveryContactName(String v){deliveryContactName=v;}public String getDeliveryContactPhone(){return deliveryContactPhone;}public void setDeliveryContactPhone(String v){deliveryContactPhone=v;}public LocalDate getEstimatedDeliveryDate(){return estimatedDeliveryDate;}public void setEstimatedDeliveryDate(LocalDate v){estimatedDeliveryDate=v;}public LocalDate getActualDeliveryDate(){return actualDeliveryDate;}public void setActualDeliveryDate(LocalDate v){actualDeliveryDate=v;}public String getDeliveryNote(){return deliveryNote;}public void setDeliveryNote(String v){deliveryNote=v;}public String getCreatedBy(){return createdBy;}public void setCreatedBy(String v){createdBy=v;}public String getUpdatedBy(){return updatedBy;}public void setUpdatedBy(String v){updatedBy=v;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}public Long getVersion(){return version;}
}