package com.trademaster.ims.mobile.payments;

import com.trademaster.ims.mobile.auth.service.CustomerAuthException;
import com.trademaster.ims.mobile.checkout.model.*;
import com.trademaster.ims.mobile.checkout.repository.*;
import com.trademaster.ims.mobile.payments.dto.PaymentDtos.*;
import com.trademaster.ims.mobile.payments.gateway.*;
import com.trademaster.ims.mobile.payments.model.*;
import com.trademaster.ims.mobile.payments.model.PaymentMethodConfiguration.MethodType;
import com.trademaster.ims.mobile.payments.repository.*;
import com.trademaster.ims.mobile.payments.service.CustomerPaymentService;
import com.trademaster.ims.model.*;
import com.trademaster.ims.repository.*;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.mockito.junit.jupiter.MockitoSettings;import org.mockito.quality.Strictness;import org.springframework.test.util.ReflectionTestUtils;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness=Strictness.LENIENT)
class CustomerPaymentServiceTest{
 @Mock CustomerOrderRepository orders;@Mock CustomerOrderStatusHistoryRepository orderHistory;@Mock PaymentMethodConfigurationRepository methods;@Mock CustomerPaymentRepository payments;@Mock PaymentAttemptRepository attempts;@Mock PaymentEventRepository events;@Mock PaymentStatusHistoryRepository histories;@Mock ManualPaymentSubmissionRepository manualSubs;@Mock PaymentReviewRepository reviews;@Mock PaymentRefundRepository refunds;@Mock PaymentReconciliationRecordRepository reconciliations;@Mock FinancialAccountRepository accounts;@Mock AccountLedgerEntryRepository ledgers;@Mock PaymentGatewayAdapter gateway;CustomerPaymentService service;
 @BeforeEach void setup(){service=new CustomerPaymentService(orders,orderHistory,methods,payments,attempts,events,histories,manualSubs,reviews,refunds,reconciliations,accounts,ledgers,gateway);lenient().when(payments.save(any())).thenAnswer(i->{CustomerPayment p=i.getArgument(0);if(p.getId()==null)ReflectionTestUtils.setField(p,"id",10L);return p;});lenient().when(attempts.save(any())).thenAnswer(i->{PaymentAttempt a=i.getArgument(0);if(a.getId()==null)ReflectionTestUtils.setField(a,"id",20L);return a;});lenient().when(histories.save(any())).thenAnswer(i->i.getArgument(0));lenient().when(reviews.save(any())).thenAnswer(i->{PaymentReview r=i.getArgument(0);if(r.getId()==null)ReflectionTestUtils.setField(r,"id",30L);return r;});lenient().when(events.save(any())).thenAnswer(i->{PaymentEvent e=i.getArgument(0);if(e.getId()==null)ReflectionTestUtils.setField(e,"id",40L);return e;});lenient().when(manualSubs.save(any())).thenAnswer(i->{ManualPaymentSubmission s=i.getArgument(0);if(s.getId()==null)ReflectionTestUtils.setField(s,"id",50L);return s;});}
 @Test void methodsExposeEligibilityWithoutSecrets(){CustomerOrder o=order();when(methods.count()).thenReturn(1L);when(orders.findByOrderNumberAndAccountId("TSS-1",7L)).thenReturn(Optional.of(o));when(methods.findByActiveTrueOrderByIdAsc()).thenReturn(List.of(method("ONLINE_GATEWAY",MethodType.ONLINE_GATEWAY),method("CASH_ON_DELIVERY",MethodType.CASH_ON_DELIVERY)));List<PaymentMethodResponse> r=service.methods(7L,"TSS-1");assertThat(r).hasSize(2);assertThat(r.get(0).eligible()).isTrue();assertThat(r.get(0).supportedCurrency()).isEqualTo("BDT");}
 @Test void initiateCreatesGatewaySessionFromServerOrderAmount(){CustomerOrder o=order();PaymentMethodConfiguration m=method("ONLINE_GATEWAY",MethodType.ONLINE_GATEWAY);when(methods.count()).thenReturn(1L);when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(methods.findByCode("ONLINE_GATEWAY")).thenReturn(Optional.of(m));when(attempts.findByAccountIdAndOrderIdAndIdempotencyKey(7L,1L,"k1")).thenReturn(Optional.empty());when(payments.findTopByOrderIdOrderByCreatedAtDesc(1L)).thenReturn(Optional.empty());when(attempts.findTopByPaymentIdOrderByAttemptNumberDesc(10L)).thenReturn(Optional.empty());when(gateway.createSession(any())).thenReturn(new PaymentGatewayAdapter.GatewaySession("LOCAL_TEST","S1","techsmart://pay",Instant.now()));PaymentInitiationResult r=service.initiate(7L,"TSS-1",new PaymentInitiationRequest("ONLINE_GATEWAY","k1",null,null));assertThat(r.amount()).isEqualByComparingTo("185.00");assertThat(r.paymentStatus()).isEqualTo("PENDING_GATEWAY");verify(gateway).createSession(argThat(x->x.amount().compareTo(new BigDecimal("185.00"))==0));}
 @Test void duplicateIdempotencyReturnsExistingAttempt(){CustomerPayment p=payment("P1");PaymentAttempt a=attempt(p);when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(order()));when(methods.count()).thenReturn(1L);when(methods.findByCode("ONLINE_GATEWAY")).thenReturn(Optional.of(method("ONLINE_GATEWAY",MethodType.ONLINE_GATEWAY)));when(attempts.findByAccountIdAndOrderIdAndIdempotencyKey(7L,1L,"same")).thenReturn(Optional.of(a));when(payments.findById(10L)).thenReturn(Optional.of(p));PaymentInitiationResult r=service.initiate(7L,"TSS-1",new PaymentInitiationRequest("ONLINE_GATEWAY","same",null,null));assertThat(r.paymentNumber()).isEqualTo("P1");verify(gateway,never()).createSession(any());}
 @Test void validWebhookMarksPaidPostsOnceAndConfirmsOrder(){CustomerOrder o=order();CustomerPayment p=payment("P1");PaymentAttempt a=attempt(p);FinancialAccount fa=new FinancialAccount();fa.setAccountId(5L);fa.setStatus(FinancialAccount.AccountStatus.ACTIVE);fa.setCurrentBalance(new BigDecimal("10.00"));when(gateway.supports("LOCAL_TEST")).thenReturn(true);when(gateway.verifyCallback("{}","sig")).thenReturn(new PaymentGatewayAdapter.VerificationResult(true,"E1","payment.succeeded","P1","TSS-1",1,"TX1",new BigDecimal("185.00"),"BDT","SUCCEEDED",null,Map.of()));when(events.findByProviderAndGatewayEventId("LOCAL_TEST","E1")).thenReturn(Optional.empty());when(payments.lockByPaymentNumber("P1")).thenReturn(Optional.of(p));when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(attempts.findByPaymentIdAndAttemptNumber(10L,1)).thenReturn(Optional.of(a));when(payments.findByGatewayTransactionId("TX1")).thenReturn(Optional.empty());when(methods.findByCode("ONLINE_GATEWAY")).thenReturn(Optional.of(method("ONLINE_GATEWAY",MethodType.ONLINE_GATEWAY)));when(payments.existsByPostingKey("CUSTOMER_PAYMENT:P1")).thenReturn(false);when(accounts.findAll()).thenReturn(List.of(fa));when(ledgers.save(any())).thenAnswer(i->{AccountLedgerEntry e=i.getArgument(0);ReflectionTestUtils.setField(e,"ledgerEntryId",99L);return e;});WebhookResult r=service.webhook("LOCAL_TEST","{}","sig");assertThat(r.paymentStatus()).isEqualTo("PAID");assertThat(o.getStatus()).isEqualTo(CustomerOrder.OrderStatus.CONFIRMED);assertThat(o.getPaymentStatus()).isEqualTo(CustomerOrder.PaymentStatus.PAID);assertThat(fa.getCurrentBalance()).isEqualByComparingTo("195.00");verify(ledgers,times(1)).save(any());}
 @Test void manualPaymentRequiresReviewAndDoesNotPost(){CustomerOrder o=order();when(methods.count()).thenReturn(1L);when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(methods.findByCode("BANK_TRANSFER")).thenReturn(Optional.of(method("BANK_TRANSFER",MethodType.BANK_TRANSFER)));when(manualSubs.findByMethodAndTransactionReference("BANK_TRANSFER","BR123")).thenReturn(Optional.empty());when(attempts.findByAccountIdAndOrderIdAndIdempotencyKey(7L,1L,"m1")).thenReturn(Optional.empty());when(payments.findTopByOrderIdOrderByCreatedAtDesc(1L)).thenReturn(Optional.empty());when(attempts.findTopByPaymentIdOrderByAttemptNumberDesc(10L)).thenReturn(Optional.empty());ManualPaymentResult r=service.manual(7L,"TSS-1",new ManualPaymentRequest("BANK_TRANSFER","BR123",new BigDecimal("185.00"),"A","01700000000",null,"m1"));assertThat(r.paymentStatus()).isEqualTo("REVIEW_REQUIRED");verify(ledgers,never()).save(any());assertThat(o.getPaymentStatus()).isEqualTo(CustomerOrder.PaymentStatus.REVIEW_REQUIRED);}
 @Test void codCreatesPendingRecordWithoutPaidOrPosting(){CustomerOrder o=order();when(methods.count()).thenReturn(1L);when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(methods.findByCode("CASH_ON_DELIVERY")).thenReturn(Optional.of(method("CASH_ON_DELIVERY",MethodType.CASH_ON_DELIVERY)));when(attempts.findByAccountIdAndOrderIdAndIdempotencyKey(7L,1L,"c1")).thenReturn(Optional.empty());when(payments.findTopByOrderIdOrderByCreatedAtDesc(1L)).thenReturn(Optional.empty());when(attempts.findTopByPaymentIdOrderByAttemptNumberDesc(10L)).thenReturn(Optional.empty());CodSelectionResult r=service.cod(7L,"TSS-1",new CodSelectionRequest("c1"));assertThat(r.paymentStatus()).isEqualTo("COD_PENDING");assertThat(o.getPaymentStatus()).isEqualTo(CustomerOrder.PaymentStatus.COD_PENDING);assertThat(o.getAccountingStatus()).isEqualTo(CustomerOrder.AccountingStatus.UNPOSTED);verify(ledgers,never()).save(any());}
 @Test void cancelPendingPaymentCancelsAttemptWithoutPosting(){CustomerOrder o=order();CustomerPayment p=payment("P1");PaymentAttempt a=attempt(p);when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(payments.findTopByOrderIdOrderByCreatedAtDesc(1L)).thenReturn(Optional.of(p));when(attempts.findTopByPaymentIdOrderByAttemptNumberDesc(10L)).thenReturn(Optional.of(a));PaymentStatusResult r=service.cancel(7L,"TSS-1");assertThat(r.paymentStatus()).isEqualTo("CANCELLED");assertThat(a.getStatus()).isEqualTo(PaymentAttempt.AttemptStatus.CANCELLED);assertThat(o.getPaymentStatus()).isEqualTo(CustomerOrder.PaymentStatus.CANCELLED);verify(ledgers,never()).save(any());} @Test void customerCannotAccessAnotherCustomersOrder(){CustomerOrder o=order();o.setAccountId(8L);when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(methods.count()).thenReturn(1L);assertThatThrownBy(()->service.initiate(7L,"TSS-1",new PaymentInitiationRequest("ONLINE_GATEWAY","k",null,null))).isInstanceOf(CustomerAuthException.class).hasMessageContaining("Order was not found");}
 private CustomerOrder order(){CustomerOrder o=new CustomerOrder();ReflectionTestUtils.setField(o,"id",1L);o.setAccountId(7L);o.setOrderNumber("TSS-1");o.setTotal(new BigDecimal("185.00"));o.setSubtotal(new BigDecimal("100.00"));o.setTax(new BigDecimal("5.00"));o.setDelivery(new BigDecimal("80.00"));o.setSubmittedAt(Instant.now());return o;}private PaymentMethodConfiguration method(String c,MethodType t){PaymentMethodConfiguration m=new PaymentMethodConfiguration();m.setCode(c);m.setDisplayName(c);m.setType(t);m.setActive(true);m.setSupportedCurrency("BDT");m.setProvider(t==MethodType.ONLINE_GATEWAY?"LOCAL_TEST":null);return m;}private CustomerPayment payment(String n){CustomerPayment p=new CustomerPayment();ReflectionTestUtils.setField(p,"id",10L);p.setPaymentNumber(n);p.setOrderId(1L);p.setOrderNumber("TSS-1");p.setAccountId(7L);p.setMethodCode("ONLINE_GATEWAY");p.setMethodType("ONLINE_GATEWAY");p.setAmount(new BigDecimal("185.00"));p.setCurrency("BDT");p.setPaymentStatus(CustomerPayment.PaymentStatus.PENDING_GATEWAY);return p;}private PaymentAttempt attempt(CustomerPayment p){PaymentAttempt a=new PaymentAttempt();ReflectionTestUtils.setField(a,"id",20L);a.setPaymentId(p.getId());a.setOrderId(1L);a.setAccountId(7L);a.setAttemptNumber(1);a.setIdempotencyKey("same");a.setMethod("ONLINE_GATEWAY");a.setAmount(p.getAmount());a.setCurrency("BDT");a.setStatus(PaymentAttempt.AttemptStatus.SESSION_CREATED);return a;}
}



