package com.trademaster.ims.mobile.payments;

import com.trademaster.ims.mobile.auth.service.CustomerAuthException;
import com.trademaster.ims.mobile.checkout.model.*;
import com.trademaster.ims.mobile.checkout.repository.*;
import com.trademaster.ims.mobile.payments.dto.PaymentDtos.*;
import com.trademaster.ims.mobile.payments.model.*;
import com.trademaster.ims.mobile.payments.model.PaymentMethodConfiguration.MethodType;
import com.trademaster.ims.mobile.payments.repository.*;
import com.trademaster.ims.mobile.payments.service.MobileWalletPaymentService;
import com.trademaster.ims.model.*;
import com.trademaster.ims.repository.*;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.mockito.junit.jupiter.MockitoSettings;import org.mockito.quality.Strictness;import org.springframework.core.env.Environment;import org.springframework.test.util.ReflectionTestUtils;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness=Strictness.LENIENT)
class MobileWalletPaymentServiceTest{
 @Mock CustomerOrderRepository orders;@Mock CustomerOrderStatusHistoryRepository orderHistory;@Mock PaymentMethodConfigurationRepository methods;@Mock MobileWalletProviderConfigurationRepository walletProviders;@Mock CustomerPaymentRepository payments;@Mock PaymentAttemptRepository attempts;@Mock PaymentStatusHistoryRepository histories;@Mock FinancialAccountRepository accounts;@Mock AccountLedgerEntryRepository ledgers;@Mock Environment env;MobileWalletPaymentService service;
 @BeforeEach void setup(){service=new MobileWalletPaymentService(orders,orderHistory,methods,walletProviders,payments,attempts,histories,accounts,ledgers,env);when(env.getActiveProfiles()).thenReturn(new String[0]);when(env.getProperty("TECHSMART_MOBILE_WALLET_SIMULATION")).thenReturn(null);when(env.getProperty("TECHSMART_MOBILE_WALLET_RESULT")).thenReturn(null);when(env.getProperty("techsmart.mobile-wallet.result","SUCCESS")).thenReturn("SUCCESS");lenient().when(methods.findByCode("MOBILE_WALLET")).thenReturn(Optional.of(method()));lenient().when(walletProviders.findByCode(anyString())).thenReturn(Optional.empty());lenient().when(walletProviders.findByCode("BKASH")).thenReturn(Optional.of(provider()));lenient().when(payments.save(any())).thenAnswer(i->{CustomerPayment p=i.getArgument(0);if(p.getId()==null)ReflectionTestUtils.setField(p,"id",10L);return p;});lenient().when(attempts.save(any())).thenAnswer(i->{PaymentAttempt a=i.getArgument(0);if(a.getId()==null)ReflectionTestUtils.setField(a,"id",20L);return a;});lenient().when(histories.save(any())).thenAnswer(i->i.getArgument(0));lenient().when(orderHistory.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void initiateCreatesSafeWalletSessionFromServerOrderAmount(){CustomerOrder o=order();when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(attempts.findByAccountIdAndOrderIdAndIdempotencyKey(7L,1L,"mw1")).thenReturn(Optional.empty());when(payments.findTopByOrderIdOrderByCreatedAtDesc(1L)).thenReturn(Optional.empty());when(attempts.findTopByPaymentIdOrderByAttemptNumberDesc(10L)).thenReturn(Optional.empty());MobileWalletSessionResult r=service.initiate(7L,"TSS-1",new MobileWalletInitiationRequest("BKASH","mw1"));assertThat(r.amount()).isEqualByComparingTo("185.00");assertThat(r.providerCode()).isEqualTo("BKASH");assertThat(r.safeInstruction()).contains("never enter real wallet credentials");verify(attempts).save(argThat(a->a.getAmount().compareTo(new BigDecimal("185.00"))==0&&a.getGatewaySessionId()!=null));}
 @Test void validConfirmMarksPaidPostsOnceAndMasksWalletNumber(){CustomerOrder o=order();CustomerPayment p=payment();PaymentAttempt a=attempt(p);FinancialAccount fa=new FinancialAccount();fa.setAccountId(5L);fa.setStatus(FinancialAccount.AccountStatus.ACTIVE);fa.setCurrentBalance(new BigDecimal("10.00"));when(attempts.findByGatewaySessionId("MW-1")).thenReturn(Optional.of(a));when(payments.lockById(10L)).thenReturn(Optional.of(p));when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(attempts.findById(20L)).thenReturn(Optional.of(a));when(payments.existsByPostingKey("CUSTOMER_PAYMENT:TSP-1")).thenReturn(false);when(accounts.findAll()).thenReturn(List.of(fa));when(ledgers.save(any())).thenAnswer(i->{AccountLedgerEntry e=i.getArgument(0);ReflectionTestUtils.setField(e,"ledgerEntryId",99L);return e;});when(attempts.findByPaymentIdOrderByAttemptNumberAsc(10L)).thenReturn(List.of(a));when(histories.findByPaymentIdOrderByOccurredAtAsc(10L)).thenReturn(List.of());PaymentStatusResult r=service.confirm(7L,"MW-1",new MobileWalletConfirmRequest("01700000000","123456","12345","confirm1"));assertThat(r.paymentStatus()).isEqualTo("PAID");assertThat(o.getAccountingStatus()).isEqualTo(CustomerOrder.AccountingStatus.POSTED);assertThat(a.getExternalReference()).isEqualTo("017****0000");verify(ledgers,times(1)).save(any());}
 @Test void invalidCredentialsDoNotPostOrMarkPaid(){CustomerOrder o=order();CustomerPayment p=payment();PaymentAttempt a=attempt(p);when(attempts.findByGatewaySessionId("MW-1")).thenReturn(Optional.of(a));when(payments.lockById(10L)).thenReturn(Optional.of(p));when(orders.lockByOrderNumber("TSS-1")).thenReturn(Optional.of(o));when(attempts.findById(20L)).thenReturn(Optional.of(a));assertThatThrownBy(()->service.confirm(7L,"MW-1",new MobileWalletConfirmRequest("01700000000","000000","00000","bad1"))).isInstanceOf(CustomerAuthException.class).hasMessageContaining("invalid");assertThat(a.getFailedCredentialAttempts()).isEqualTo(1);assertThat(p.getPaymentStatus()).isEqualTo(CustomerPayment.PaymentStatus.PENDING_GATEWAY);verify(ledgers,never()).save(any());}
 private CustomerOrder order(){CustomerOrder o=new CustomerOrder();ReflectionTestUtils.setField(o,"id",1L);o.setAccountId(7L);o.setOrderNumber("TSS-1");o.setTotal(new BigDecimal("185.00"));o.setSubtotal(new BigDecimal("100.00"));o.setTax(new BigDecimal("5.00"));o.setDelivery(new BigDecimal("80.00"));o.setSubmittedAt(Instant.now());return o;}private PaymentMethodConfiguration method(){PaymentMethodConfiguration m=new PaymentMethodConfiguration();m.setCode("MOBILE_WALLET");m.setDisplayName("Mobile Wallet");m.setType(MethodType.MOBILE_WALLET);m.setActive(true);m.setSupportedCurrency("BDT");return m;}private MobileWalletProviderConfiguration provider(){MobileWalletProviderConfiguration p=new MobileWalletProviderConfiguration();p.setCode("BKASH");p.setDisplayName("bKash");p.setShortDescription("Wallet");p.setActive(true);p.setSimulationEnabled(true);p.setDisplayOrder(1);p.setSupportedCurrency("BDT");return p;}private CustomerPayment payment(){CustomerPayment p=new CustomerPayment();ReflectionTestUtils.setField(p,"id",10L);p.setPaymentNumber("TSP-1");p.setOrderId(1L);p.setOrderNumber("TSS-1");p.setAccountId(7L);p.setMethodCode("MOBILE_WALLET");p.setMethodType("MOBILE_WALLET");p.setGatewayProvider("BKASH");p.setAmount(new BigDecimal("185.00"));p.setCurrency("BDT");p.setPaymentStatus(CustomerPayment.PaymentStatus.PENDING_GATEWAY);return p;}private PaymentAttempt attempt(CustomerPayment p){PaymentAttempt a=new PaymentAttempt();ReflectionTestUtils.setField(a,"id",20L);a.setPaymentId(p.getId());a.setOrderId(1L);a.setAccountId(7L);a.setAttemptNumber(1);a.setIdempotencyKey("mw1");a.setMethod("MOBILE_WALLET");a.setProvider("BKASH");a.setAmount(p.getAmount());a.setCurrency("BDT");a.setStatus(PaymentAttempt.AttemptStatus.SESSION_CREATED);a.setGatewaySessionId("MW-1");a.setExpiresAt(Instant.now().plusSeconds(600));return a;}
}
