package com.trademaster.ims.mobile.shopping;
import com.trademaster.ims.config.SecurityConfig; import com.trademaster.ims.mobile.auth.security.*; import com.trademaster.ims.mobile.common.exception.MobileExceptionHandler; import com.trademaster.ims.mobile.shopping.controller.CustomerShoppingController; import com.trademaster.ims.mobile.shopping.dto.ShoppingDtos.*; import com.trademaster.ims.mobile.shopping.service.CustomerShoppingService; import com.trademaster.ims.security.*; import jakarta.servlet.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest; import org.springframework.context.annotation.*; import org.springframework.test.context.ContextConfiguration; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.test.web.servlet.MockMvc; import java.math.BigDecimal; import java.time.Instant; import java.util.List;
import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@WebMvcTest(CustomerShoppingController.class) @Import({SecurityConfig.class,MobileExceptionHandler.class}) @ContextConfiguration(classes={CustomerShoppingController.class,SecurityConfig.class,MobileExceptionHandler.class})
class CustomerShoppingSecurityTest {
 @Autowired MockMvc mvc; @MockitoBean CustomerShoppingService service; @MockitoBean UserDetailsServiceImpl users; @MockitoBean JwtUtils jwt; @MockitoBean CustomerAuthTokenFilter customerFilter;
 @BeforeEach void setup()throws Exception{doAnswer(i->{((FilterChain)i.getArgument(2)).doFilter((ServletRequest)i.getArgument(0),(ServletResponse)i.getArgument(1));return null;}).when(customerFilter).doFilter(any(),any(),any());when(service.accountId(any())).thenReturn(7L);when(service.getCart(eq(7L),any())).thenReturn(new CartResponse(1L,List.of(),0,0,BigDecimal.ZERO,List.of(),Instant.now()));}
 @Test void anonymousCannotReadCart()throws Exception{mvc.perform(get("/api/mobile/v1/cart")).andExpect(status().isUnauthorized());}
 @Test void employeeCannotReadCart()throws Exception{mvc.perform(get("/api/mobile/v1/cart").with(user("employee").roles("EMPLOYEE"))).andExpect(status().isForbidden());}
 @Test void customerCanReadOnlyPrincipalCart()throws Exception{mvc.perform(get("/api/mobile/v1/cart").with(authentication(new CustomerAuthentication(7L)))).andExpect(status().isOk()).andExpect(jsonPath("$.cartId").value(1));verify(service).getCart(eq(7L),any());}
 @Test void requestCannotSupplyCustomerIdentity()throws Exception{when(service.addCartItem(eq(7L),any(),any())).thenReturn(new CartResponse(1L,List.of(),0,0,BigDecimal.ZERO,List.of(),Instant.now()));mvc.perform(post("/api/mobile/v1/cart/items").with(authentication(new CustomerAuthentication(7L))).contentType("application/json").content("{\"productId\":1,\"quantity\":1,\"customerId\":999}")).andExpect(status().isOk());verify(service).addCartItem(eq(7L),any(),any());}
}
