package com.trademaster.ims.mobile.auth.service;

import com.trademaster.ims.mobile.auth.dto.CustomerAuthDtos.*;
import com.trademaster.ims.mobile.auth.model.*;
import com.trademaster.ims.mobile.auth.repository.*;
import com.trademaster.ims.mobile.auth.security.*;import com.trademaster.ims.mobile.notifications.service.CustomerNotificationService;
import com.trademaster.ims.model.Customer;
import com.trademaster.ims.repository.CustomerRepository;
import org.slf4j.*;
import org.springframework.beans.factory.annotation.Autowired;import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;
import java.util.regex.Pattern;

@Service
public class CustomerAuthService {
 private static final Logger log=LoggerFactory.getLogger(CustomerAuthService.class);
 private static final SecureRandom RANDOM=new SecureRandom();
 private static final Pattern PASSWORD=Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{8,72}$");
 private final CustomerAccountRepository accounts; private final CustomerRepository customers; private final CustomerAuthOtpRepository otps; private final CustomerRefreshTokenRepository refreshTokens; private final CustomerResetAuthorizationRepository resets; private final PasswordEncoder encoder; private final CustomerJwtService jwt; private final CustomerAuthMailService mail; @Autowired(required=false) private CustomerNotificationService notifications;
 @Value("${app.customer-auth.otp-expiry-minutes:10}") private long otpMinutes;
 @Value("${app.customer-auth.otp-max-attempts:5}") private int otpMaxAttempts;
 @Value("${app.customer-auth.otp-resend-cooldown-seconds:45}") private long resendCooldown;
 @Value("${app.customer-auth.otp-max-resends:5}") private int maxResends;
 @Value("${app.customer-auth.refresh-token-days:30}") private long refreshDays;
 @Value("${app.customer-auth.reset-token-minutes:10}") private long resetMinutes;
 @Value("${app.customer-auth.max-login-failures:5}") private int maxLoginFailures;
 @Value("${app.customer-auth.lockout-minutes:15}") private long lockoutMinutes;
 public CustomerAuthService(CustomerAccountRepository a,CustomerRepository c,CustomerAuthOtpRepository o,CustomerRefreshTokenRepository r,CustomerResetAuthorizationRepository x,PasswordEncoder e,CustomerJwtService j,CustomerAuthMailService m){accounts=a;customers=c;otps=o;refreshTokens=r;resets=x;encoder=e;jwt=j;mail=m;}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public PendingVerificationResponse register(RegisterRequest r){String email=email(r.email());String phone=phone(r.phone());password(r.password(),r.confirmPassword(),email);CustomerAccount a=accounts.findByEmailIgnoreCase(email).orElse(null);if(a!=null&&a.getStatus()!=CustomerAccount.Status.PENDING_VERIFICATION)throw err(HttpStatus.CONFLICT,"EMAIL_ALREADY_REGISTERED","An account already exists for this email.");if(a==null){Customer customer=resolveCustomerForRegistration(email,r.fullName().trim(),phone);a=new CustomerAccount();a.setCustomer(customer);a.setEmail(email);}else{enforceResendEligibility(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY);Customer c=a.getCustomer();c.setCustomerName(r.fullName().trim());c.setPhone(phone);c.setMobile(phone);customers.save(c);}a.setPasswordHash(encoder.encode(r.password()));a.setStatus(CustomerAccount.Status.PENDING_VERIFICATION);a.setEmailVerified(false);a=accounts.save(a);CustomerAuthOtp otp=issueOtp(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY,0);try{mail.registrationOtp(a,a.getCustomer().getCustomerName(),takeOtp(),otpMinutes);}catch(CustomerAuthException ex){otp.setConsumedAt(Instant.now());otps.save(otp);throw ex;}event("REGISTRATION_INITIATED",a);return pending(a,otp);}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public AuthResponse verifyRegistration(EmailOtpRequest r){CustomerAccount a=account(r.email());if(a.getStatus()!=CustomerAccount.Status.PENDING_VERIFICATION)throw err(HttpStatus.BAD_REQUEST,"OTP_INVALID","Verification request is not active.");verifyOtp(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY,r.otp());a.setEmailVerified(true);a.setStatus(CustomerAccount.Status.ACTIVE);a.setFailedLoginAttempts(0);accounts.save(a);event("REGISTRATION_VERIFIED",a);return newSession(a,null);}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public PendingVerificationResponse resendRegistration(EmailRequest r){CustomerAccount a=account(r.email());if(a.getStatus()!=CustomerAccount.Status.PENDING_VERIFICATION)throw err(HttpStatus.BAD_REQUEST,"OTP_INVALID","Verification request is not active.");CustomerAuthOtp previous=enforceResendEligibility(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY);consumeActive(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY);CustomerAuthOtp otp=issueOtp(a,CustomerAuthOtp.Purpose.REGISTRATION_VERIFY,previous==null?1:previous.getResendCount()+1);try{mail.registrationOtp(a,a.getCustomer().getCustomerName(),takeOtp(),otpMinutes);}catch(CustomerAuthException ex){otp.setConsumedAt(Instant.now());otps.save(otp);throw ex;}event("OTP_RESEND_REQUESTED",a);return pending(a,otp);}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public AuthResponse login(LoginRequest r){String email=email(r.email());CustomerAccount a=accounts.findByEmailIgnoreCase(email).orElse(null);if(a==null){fakePasswordCheck(r.password());throw invalidCredentials();}if(a.getStatus()==CustomerAccount.Status.PENDING_VERIFICATION)throw err(HttpStatus.FORBIDDEN,"ACCOUNT_PENDING_VERIFICATION","Email verification is required before login.");if(a.getStatus()==CustomerAccount.Status.DISABLED)throw err(HttpStatus.FORBIDDEN,"ACCOUNT_DISABLED","This account is unavailable.");if(a.getLockedUntil()!=null&&a.getLockedUntil().isAfter(Instant.now()))throw err(HttpStatus.LOCKED,"ACCOUNT_LOCKED","Too many login attempts. Please try again later.");if(!encoder.matches(r.password(),a.getPasswordHash())){int failures=a.getFailedLoginAttempts()+1;a.setFailedLoginAttempts(failures);if(failures>=maxLoginFailures){a.setStatus(CustomerAccount.Status.LOCKED);a.setLockedUntil(Instant.now().plus(Duration.ofMinutes(lockoutMinutes)));event("ACCOUNT_LOCKED",a);}accounts.save(a);event("LOGIN_FAILURE",a);throw invalidCredentials();}a.setStatus(CustomerAccount.Status.ACTIVE);a.setLockedUntil(null);a.setFailedLoginAttempts(0);a.setLastLoginAt(Instant.now());accounts.save(a);event("LOGIN_SUCCESS",a);return newSession(a,safeDevice(r.deviceDescription()));}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public TokenResponse refresh(RefreshRequest r){String hash=hash(r.refreshToken());CustomerRefreshToken old=refreshTokens.findByTokenHash(hash).orElseThrow(()->err(HttpStatus.UNAUTHORIZED,"REFRESH_TOKEN_INVALID","The session is invalid."));if(old.getRevokedAt()!=null){revokeFamily(old.getTokenFamilyId());event("REFRESH_TOKEN_REUSE_DETECTED",old.getAccount());throw err(HttpStatus.UNAUTHORIZED,"SESSION_REVOKED","The session has been revoked.");}if(old.getExpiresAt().isBefore(Instant.now())){old.setRevokedAt(Instant.now());refreshTokens.save(old);throw err(HttpStatus.UNAUTHORIZED,"REFRESH_TOKEN_EXPIRED","The session has expired.");}CustomerAccount a=old.getAccount();ensureActive(a);old.setRevokedAt(Instant.now());refreshTokens.save(old);IssuedSession n=issueSession(a,old.getTokenFamilyId(),safeDevice(r.deviceDescription()));old.setReplacedByTokenId(n.refreshEntity().getId());refreshTokens.save(old);return new TokenResponse(n.access().token(),n.rawRefresh(),n.access().expiresAt(),n.refreshEntity().getExpiresAt());}

 @Transactional public MessageResponse logout(Long accountId,LogoutRequest r){if(r.refreshToken()!=null&&!r.refreshToken().isBlank())refreshTokens.findByTokenHash(hash(r.refreshToken())).filter(t->t.getAccount().getId().equals(accountId)).ifPresent(t->{if(t.getRevokedAt()==null){t.setRevokedAt(Instant.now());refreshTokens.save(t);}});event("LOGOUT",accounts.findById(accountId).orElse(null));return message("You have been logged out.");}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public MessageResponse forgotPassword(EmailRequest r){String email=email(r.email());CustomerAccount a=accounts.findByEmailIgnoreCase(email).orElse(null);if(a==null||a.getStatus()==CustomerAccount.Status.DISABLED)return genericForgot();CustomerAuthOtp previous=enforceResendEligibility(a,CustomerAuthOtp.Purpose.PASSWORD_RESET);consumeActive(a,CustomerAuthOtp.Purpose.PASSWORD_RESET);CustomerAuthOtp otp=issueOtp(a,CustomerAuthOtp.Purpose.PASSWORD_RESET,previous==null?0:previous.getResendCount()+1);try{mail.passwordResetOtp(a,a.getCustomer().getCustomerName(),takeOtp(),otpMinutes);}catch(CustomerAuthException ex){otp.setConsumedAt(Instant.now());otps.save(otp);throw ex;}event("FORGOT_PASSWORD_REQUESTED",a);return genericForgot();}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public ResetAuthorizationResponse verifyResetOtp(EmailOtpRequest r){CustomerAccount a=account(r.email());verifyOtp(a,CustomerAuthOtp.Purpose.PASSWORD_RESET,r.otp());byte[] raw=new byte[32];RANDOM.nextBytes(raw);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(raw);CustomerResetAuthorization x=new CustomerResetAuthorization();x.setAccount(a);x.setTokenHash(hash(token));x.setExpiresAt(Instant.now().plus(Duration.ofMinutes(resetMinutes)));resets.save(x);return new ResetAuthorizationResponse(token,x.getExpiresAt());}

 @Transactional(noRollbackFor=CustomerAuthException.class)
 public MessageResponse resetPassword(ResetPasswordRequest r){password(r.newPassword(),r.confirmPassword(),null);CustomerResetAuthorization x=resets.findByTokenHash(hash(r.resetToken())).orElseThrow(()->err(HttpStatus.BAD_REQUEST,"RESET_TOKEN_INVALID","Reset authorization is invalid."));if(x.getConsumedAt()!=null)throw err(HttpStatus.BAD_REQUEST,"RESET_TOKEN_INVALID","Reset authorization has already been used.");if(x.getExpiresAt().isBefore(Instant.now()))throw err(HttpStatus.BAD_REQUEST,"RESET_TOKEN_EXPIRED","Reset authorization has expired.");CustomerAccount a=x.getAccount();if(encoder.matches(r.newPassword(),a.getPasswordHash()))throw err(HttpStatus.BAD_REQUEST,"PASSWORD_REUSE_NOT_ALLOWED","New password must differ from the current password.");a.setPasswordHash(encoder.encode(r.newPassword()));a.setPasswordChangedAt(Instant.now());a.setFailedLoginAttempts(0);a.setLockedUntil(null);a.setStatus(CustomerAccount.Status.ACTIVE);accounts.save(a);x.setConsumedAt(Instant.now());resets.save(x);revokeAll(a.getId());mail.passwordChanged(a,a.getCustomer().getCustomerName());event("PASSWORD_RESET",a);notifyPasswordChanged(a.getId());return message("Password reset successfully. Please sign in.");}

 @Transactional(readOnly=true) public CustomerProfileResponse profile(Long accountId){return profileOf(requiredActive(accountId));}
 @Transactional public CustomerProfileResponse updateProfile(Long accountId,ProfileUpdateRequest r){CustomerAccount a=requiredActive(accountId);Customer c=a.getCustomer();c.setCustomerName(r.fullName().trim());c.setPhone(phone(r.phone()));c.setMobile(c.getPhone());c.setAddress(clean(r.address()));c.setCity(clean(r.city()));c.setState(clean(r.state()));c.setPostalCode(clean(r.postalCode()));c.setCountry(clean(r.country()));customers.save(c);event("PROFILE_UPDATED",a);notifyProfileUpdated(a.getId());return profileOf(a);}
 @Transactional(noRollbackFor=CustomerAuthException.class) public MessageResponse changePassword(Long accountId,ChangePasswordRequest r){CustomerAccount a=requiredActive(accountId);if(!encoder.matches(r.currentPassword(),a.getPasswordHash()))throw err(HttpStatus.BAD_REQUEST,"CURRENT_PASSWORD_INCORRECT","Current password is incorrect.");password(r.newPassword(),r.confirmPassword(),a.getEmail());if(encoder.matches(r.newPassword(),a.getPasswordHash()))throw err(HttpStatus.BAD_REQUEST,"PASSWORD_REUSE_NOT_ALLOWED","New password must differ from the current password.");a.setPasswordHash(encoder.encode(r.newPassword()));a.setPasswordChangedAt(Instant.now());accounts.save(a);revokeAll(a.getId());mail.passwordChanged(a,a.getCustomer().getCustomerName());event("PASSWORD_CHANGED",a);notifyPasswordChanged(a.getId());return message("Password changed. Please sign in again.");}

 private void notifyProfileUpdated(Long id){if(notifications!=null&&id!=null)notifications.profileUpdated(id);}
 private void notifyPasswordChanged(Long id){if(notifications!=null&&id!=null)notifications.passwordChanged(id);}
 private final ThreadLocal<String> otpPlain=new ThreadLocal<>();
 private String takeOtp(){String value=otpPlain.get();otpPlain.remove();return value;}
 private CustomerAuthOtp issueOtp(CustomerAccount a,CustomerAuthOtp.Purpose purpose,int resends){consumeActive(a,purpose);String raw=String.format("%06d",RANDOM.nextInt(1_000_000));CustomerAuthOtp o=new CustomerAuthOtp();o.setAccount(a);o.setPurpose(purpose);o.setOtpHash(encoder.encode(raw));o.setExpiresAt(Instant.now().plus(Duration.ofMinutes(otpMinutes)));o.setMaxAttempts(otpMaxAttempts);o.setResendCount(resends);o.setLastSentAt(Instant.now());otpPlain.set(raw);return otps.save(o);}
 private void verifyOtp(CustomerAccount a,CustomerAuthOtp.Purpose purpose,String raw){CustomerAuthOtp o=otps.findTopByAccountIdAndPurposeOrderByCreatedAtDesc(a.getId(),purpose).orElseThrow(()->err(HttpStatus.BAD_REQUEST,"OTP_INVALID","Verification code is invalid."));if(o.getConsumedAt()!=null)throw err(HttpStatus.BAD_REQUEST,"OTP_INVALID","Verification code has already been used.");if(o.getExpiresAt().isBefore(Instant.now())){o.setConsumedAt(Instant.now());otps.save(o);throw err(HttpStatus.BAD_REQUEST,"OTP_EXPIRED","Verification code has expired.");}if(o.getAttempts()>=o.getMaxAttempts())throw err(HttpStatus.TOO_MANY_REQUESTS,"OTP_ATTEMPTS_EXCEEDED","Too many verification attempts.");if(!encoder.matches(raw,o.getOtpHash())){o.setAttempts(o.getAttempts()+1);if(o.getAttempts()>=o.getMaxAttempts())o.setConsumedAt(Instant.now());otps.save(o);event("OTP_VERIFICATION_FAILED",a);throw err(HttpStatus.BAD_REQUEST,o.getAttempts()>=o.getMaxAttempts()?"OTP_ATTEMPTS_EXCEEDED":"OTP_INVALID",o.getAttempts()>=o.getMaxAttempts()?"Too many verification attempts.":"Verification code is invalid.");}o.setConsumedAt(Instant.now());otps.save(o);}
 private CustomerAuthOtp enforceResendEligibility(CustomerAccount a,CustomerAuthOtp.Purpose p){CustomerAuthOtp o=otps.findTopByAccountIdAndPurposeOrderByCreatedAtDesc(a.getId(),p).orElse(null);if(o==null)return null;if(o.getLastSentAt().plusSeconds(resendCooldown).isAfter(Instant.now()))throw err(HttpStatus.TOO_MANY_REQUESTS,"OTP_RESEND_COOLDOWN","Please wait before requesting another code.");if(o.getResendCount()>=maxResends)throw err(HttpStatus.TOO_MANY_REQUESTS,"OTP_RESEND_LIMIT_REACHED","Verification-code resend limit reached.");return o;}
 private void consumeActive(CustomerAccount a,CustomerAuthOtp.Purpose p){for(CustomerAuthOtp o:otps.findByAccountIdAndPurposeAndConsumedAtIsNull(a.getId(),p)){o.setConsumedAt(Instant.now());otps.save(o);}}
 private AuthResponse newSession(CustomerAccount a,String device){IssuedSession s=issueSession(a,UUID.randomUUID().toString(),device);return new AuthResponse(s.access().token(),s.rawRefresh(),s.access().expiresAt(),s.refreshEntity().getExpiresAt(),profileOf(a));}
 private IssuedSession issueSession(CustomerAccount a,String family,String device){CustomerJwtService.IssuedAccess access=jwt.issue(a.getId());byte[] raw=new byte[48];RANDOM.nextBytes(raw);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(raw);CustomerRefreshToken t=new CustomerRefreshToken();t.setAccount(a);t.setTokenHash(hash(token));t.setTokenFamilyId(family);t.setIssuedAt(Instant.now());t.setExpiresAt(Instant.now().plus(Duration.ofDays(refreshDays)));t.setDeviceDescription(device);t=refreshTokens.save(t);return new IssuedSession(access,token,t);}
 private record IssuedSession(CustomerJwtService.IssuedAccess access,String rawRefresh,CustomerRefreshToken refreshEntity){}
 private Customer resolveCustomerForRegistration(String email,String name,String phone){List<Customer> matches=customers.findByEmailIgnoreCase(email);if(matches.size()>1)throw err(HttpStatus.CONFLICT,"CUSTOMER_LINK_REVIEW_REQUIRED","This email matches multiple customer records. Please contact support.");if(matches.size()==1){Customer c=matches.get(0);if(accounts.existsByCustomerCustomerId(c.getCustomerId()))throw err(HttpStatus.CONFLICT,"EMAIL_ALREADY_REGISTERED","An account already exists for this customer.");return c;}Customer c=new Customer();c.setCustomerCode("CUST-APP-"+System.currentTimeMillis()+"-"+(1000+RANDOM.nextInt(9000)));c.setCustomerName(name);c.setEmail(email);c.setPhone(phone);c.setMobile(phone);c.setCustomerType(Customer.CustomerType.RETAIL);c.setStatus(true);return customers.save(c);}
 private CustomerProfileResponse profileOf(CustomerAccount a){Customer c=a.getCustomer();return new CustomerProfileResponse(c.getCustomerId(),c.getCustomerCode(),c.getCustomerName(),a.getEmail(),c.getPhone(),c.getCustomerType().name(),c.getAddress(),c.getCity(),c.getState(),c.getPostalCode(),c.getCountry(),c.getPhotoUrl(),a.isEmailVerified());}
 private CustomerAccount account(String e){return accounts.findByEmailIgnoreCase(email(e)).orElseThrow(()->err(HttpStatus.BAD_REQUEST,"OTP_INVALID","Verification request is invalid."));}
 private CustomerAccount requiredActive(Long id){CustomerAccount a=accounts.findById(id).orElseThrow(()->err(HttpStatus.UNAUTHORIZED,"AUTHENTICATION_REQUIRED","Authentication is required."));ensureActive(a);return a;}
 private void ensureActive(CustomerAccount a){if(a.getStatus()!=CustomerAccount.Status.ACTIVE||!a.isEmailVerified())throw err(HttpStatus.UNAUTHORIZED,"SESSION_REVOKED","The customer session is unavailable.");}
 private void revokeAll(Long id){for(CustomerRefreshToken t:refreshTokens.findByAccountIdAndRevokedAtIsNull(id)){t.setRevokedAt(Instant.now());refreshTokens.save(t);}}
 private void revokeFamily(String family){for(CustomerRefreshToken t:refreshTokens.findByTokenFamilyIdAndRevokedAtIsNull(family)){t.setRevokedAt(Instant.now());refreshTokens.save(t);}}
 private PendingVerificationResponse pending(CustomerAccount a,CustomerAuthOtp o){return new PendingVerificationResponse(mask(a.getEmail()),Duration.between(Instant.now(),o.getExpiresAt()).toSeconds(),resendCooldown);}
 private MessageResponse genericForgot(){return message("If an eligible account exists, a verification code has been sent.");}
 private MessageResponse message(String s){return new MessageResponse(s);}
 private String email(String s){if(s==null)return "";return s.trim().toLowerCase(Locale.ROOT);}
 private String phone(String s){String v=s==null?"":s.replaceAll("[\\s()-]","");if(v.startsWith("+880"))v="0"+v.substring(4);if(!v.matches("01[3-9]\\d{8}"))throw err(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Enter a valid Bangladesh phone number.");return v;}
 private void password(String p,String confirm,String email){if(!Objects.equals(p,confirm)||p==null||!PASSWORD.matcher(p).matches()||(email!=null&&p.equalsIgnoreCase(email)))throw err(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Password must be 8-72 characters and include uppercase, lowercase, number, and special character.");}
 private String clean(String s){return s==null?null:s.trim();} private String safeDevice(String s){if(s==null)return null;String v=s.trim();return v.substring(0,Math.min(200,v.length()));}
 private String mask(String e){int at=e.indexOf('@');if(at<1)return "***";return e.substring(0,1)+"***"+e.substring(at);}
 private String hash(String raw){if(raw==null||raw.isBlank())throw err(HttpStatus.UNAUTHORIZED,"REFRESH_TOKEN_INVALID","The session is invalid.");try{byte[] h=MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(h);}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private void fakePasswordCheck(String p){encoder.matches(p==null?"":p,"$2a$10$7EqJtq98hPqEX7fNZaFWoO5QeMaQvY0zR.N6uQvB6vLkYJQwH8y6K");}
 private CustomerAuthException invalidCredentials(){return err(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Email or password is incorrect.");}
 private CustomerAuthException err(HttpStatus s,String c,String m){return new CustomerAuthException(s,c,m);}
 private void event(String name,CustomerAccount a){log.info("Customer security event: event={}, accountId={}",name,a==null?null:a.getId());}
}
