package com.trademaster.ims.mobile.shopping.service;

import com.trademaster.ims.mobile.auth.security.CustomerAuthentication;
import com.trademaster.ims.mobile.auth.service.CustomerAuthException;
import com.trademaster.ims.mobile.catalog.service.MobileImageUrlService;
import com.trademaster.ims.mobile.offers.service.OfferPricingService;
import com.trademaster.ims.mobile.shopping.dto.ShoppingDtos.*;
import com.trademaster.ims.mobile.shopping.model.*;
import com.trademaster.ims.mobile.shopping.repository.*;
import com.trademaster.ims.model.*;
import com.trademaster.ims.repository.*;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.*;

@Service @Transactional
public class CustomerShoppingService {
 private static final Logger log=LoggerFactory.getLogger(CustomerShoppingService.class);
 private final CustomerCartRepository carts; private final CustomerCartItemRepository cartItems; private final CustomerWishlistRepository wishlists; private final CustomerWishlistItemRepository wishlistItems; private final ShoppingMergeReceiptRepository receipts;
 private final ProductRepository products; private final ProductVariationRepository variations; private final InventoryRepository inventory; private final CategoryRepository categories; private final MobileImageUrlService images; private final OfferPricingService offerPricing;
 public CustomerShoppingService(CustomerCartRepository a,CustomerCartItemRepository b,CustomerWishlistRepository c,CustomerWishlistItemRepository d,ShoppingMergeReceiptRepository e,ProductRepository f,ProductVariationRepository g,InventoryRepository h,CategoryRepository i,MobileImageUrlService j,OfferPricingService k){carts=a;cartItems=b;wishlists=c;wishlistItems=d;receipts=e;products=f;variations=g;inventory=h;categories=i;images=j;offerPricing=k;}

 public Long accountId(Authentication auth){if(auth instanceof CustomerAuthentication customer)return customer.accountId();throw error(HttpStatus.UNAUTHORIZED,"AUTHENTICATION_REQUIRED","Customer authentication is required.");}
 public CartResponse getCart(Long account,HttpServletRequest request){return mapCart(cart(account),List.of(),request);}
 public CartResponse addCartItem(Long account,AddCartItemRequest input,HttpServletRequest request){CustomerCart cart=cart(account); Validated value=validated(input.productId(),input.variationId(),true); CustomerCartItem item=cartItems.findByCartIdAndProductIdAndVariationKey(cart.getId(),input.productId(),key(input.variationId())).orElseGet(()->newItem(cart,input.productId(),input.variationId()));int quantity=item.getQuantity()+input.quantity();if(quantity>99)throw error(HttpStatus.BAD_REQUEST,"INVALID_QUANTITY","Combined quantity cannot exceed 99.");item.setQuantity(quantity);cartItems.save(item);log.info("Customer cart item added account={} product={}",account,input.productId());return mapCart(cart,List.of(),request);}
 public CartResponse updateCartItem(Long account,Long itemId,UpdateCartItemQuantityRequest input,HttpServletRequest request){CustomerCart cart=cart(account);CustomerCartItem item=cartItems.findByIdAndCartId(itemId,cart.getId()).orElseThrow(()->error(HttpStatus.NOT_FOUND,"CART_ITEM_NOT_FOUND","Cart item was not found."));validated(item.getProductId(),item.getVariationId(),true);item.setQuantity(input.quantity());cartItems.save(item);log.info("Customer cart quantity changed account={} item={}",account,itemId);return mapCart(cart,List.of(),request);}
 public CartResponse removeCartItem(Long account,Long itemId,HttpServletRequest request){CustomerCart cart=cart(account);cartItems.findByIdAndCartId(itemId,cart.getId()).ifPresent(cartItems::delete);log.info("Customer cart item removed account={} item={}",account,itemId);return mapCart(cart,List.of(),request);}
 public CartResponse clearCart(Long account,HttpServletRequest request){CustomerCart cart=cart(account);cartItems.deleteByCartId(cart.getId());log.info("Customer cart cleared account={}",account);return mapCart(cart,List.of(),request);}
 public CartResponse mergeCart(Long account,MergeSessionCartRequest input,HttpServletRequest request){CustomerCart cart=cart(account);if(receipts.existsByCustomerAccountIdAndMergeTypeAndRequestId(account,"CART",input.requestId()))return mapCart(cart,List.of(),request);saveReceipt(account,"CART",input.requestId());List<ValidationWarning> warnings=new ArrayList<>();for(MergeCartItemRequest candidate:input.items()){try{validated(candidate.productId(),candidate.variationId(),true);CustomerCartItem item=cartItems.findByCartIdAndProductIdAndVariationKey(cart.getId(),candidate.productId(),key(candidate.variationId())).orElseGet(()->newItem(cart,candidate.productId(),candidate.variationId()));int requested=item.getQuantity()+candidate.quantity();if(requested>99)warnings.add(warn(candidate.productId(),candidate.variationId(),"QUANTITY_ADJUSTED","Quantity was capped at 99."));item.setQuantity(Math.min(99,requested));cartItems.save(item);}catch(CustomerAuthException ex){warnings.add(warn(candidate.productId(),candidate.variationId(),ex.code(),ex.getMessage()));}}log.info("Guest cart merged account={} lines={}",account,input.items().size());return mapCart(cart,warnings,request);}
 public CartResponse validateCart(Long account,HttpServletRequest request){CustomerCart cart=cart(account);return mapCart(cart,List.of(),request);}

 public WishlistResponse getWishlist(Long account,HttpServletRequest request){return mapWishlist(wishlist(account),List.of(),request);}
 public WishlistResponse addWishlist(Long account,AddWishlistItemRequest input,HttpServletRequest request){CustomerWishlist list=wishlist(account);validated(input.productId(),null,false);if(!wishlistItems.existsByWishlistIdAndProductId(list.getId(),input.productId())){CustomerWishlistItem item=new CustomerWishlistItem();item.setWishlistId(list.getId());item.setProductId(input.productId());wishlistItems.save(item);log.info("Customer wishlist item added account={} product={}",account,input.productId());}return mapWishlist(list,List.of(),request);}
 public WishlistResponse removeWishlist(Long account,Long productId,HttpServletRequest request){CustomerWishlist list=wishlist(account);wishlistItems.deleteByWishlistIdAndProductId(list.getId(),productId);log.info("Customer wishlist item removed account={} product={}",account,productId);return mapWishlist(list,List.of(),request);}
 public WishlistResponse clearWishlist(Long account,HttpServletRequest request){CustomerWishlist list=wishlist(account);wishlistItems.deleteByWishlistId(list.getId());return mapWishlist(list,List.of(),request);}
 public WishlistResponse mergeWishlist(Long account,MergeSessionWishlistRequest input,HttpServletRequest request){CustomerWishlist list=wishlist(account);if(receipts.existsByCustomerAccountIdAndMergeTypeAndRequestId(account,"WISHLIST",input.requestId()))return mapWishlist(list,List.of(),request);saveReceipt(account,"WISHLIST",input.requestId());List<ValidationWarning>warnings=new ArrayList<>();for(Long productId:new LinkedHashSet<>(input.productIds())){try{validated(productId,null,false);if(!wishlistItems.existsByWishlistIdAndProductId(list.getId(),productId)){CustomerWishlistItem item=new CustomerWishlistItem();item.setWishlistId(list.getId());item.setProductId(productId);wishlistItems.save(item);}}catch(CustomerAuthException ex){warnings.add(warn(productId,null,ex.code(),ex.getMessage()));}}log.info("Guest wishlist merged account={} items={}",account,input.productIds().size());return mapWishlist(list,warnings,request);}

 private CustomerCart cart(Long account){return carts.findByCustomerAccountIdAndStatus(account,CustomerCart.Status.ACTIVE).orElseGet(()->{CustomerCart value=new CustomerCart();value.setCustomerAccountId(account);CustomerCart saved=carts.save(value);log.info("Customer cart created account={}",account);return saved;});}
 private CustomerWishlist wishlist(Long account){return wishlists.findByCustomerAccountId(account).orElseGet(()->{CustomerWishlist value=new CustomerWishlist();value.setCustomerAccountId(account);return wishlists.save(value);});}
 private CustomerCartItem newItem(CustomerCart cart,Long productId,Long variationId){CustomerCartItem item=new CustomerCartItem();item.setCartId(cart.getId());item.setProductId(productId);item.setVariationId(variationId);item.setQuantity(0);return item;}
 private long key(Long variationId){return variationId==null?0L:variationId;}
 private Validated validated(Long productId,Long variationId,boolean requireStock){Product product=products.findByIdAndStatus(productId,Product.ProductStatus.ACTIVE).orElseThrow(()->error(HttpStatus.BAD_REQUEST,"PRODUCT_NOT_AVAILABLE","Product is not available."));ProductVariation variation=null;if(variationId!=null){variation=variations.findById(variationId).orElseThrow(()->error(HttpStatus.BAD_REQUEST,"VARIATION_NOT_FOUND","Variation was not found."));if(!Objects.equals(variation.getProductId(),productId))throw error(HttpStatus.BAD_REQUEST,"VARIATION_NOT_FOUND","Variation does not belong to this product.");if(!variation.isActive())throw error(HttpStatus.BAD_REQUEST,"VARIATION_NOT_AVAILABLE","Variation is not available.");}long available=available(productId);if(requireStock&&available<=0)throw error(HttpStatus.CONFLICT,"PRODUCT_OUT_OF_STOCK","Product is out of stock.");return new Validated(product,variation,available);}
 private long available(Long productId){return inventory.aggregateAvailableByProductIds(List.of(productId)).stream().findFirst().map(InventoryRepository.ProductStockTotal::getAvailableQuantity).orElse(0L);}
 private CartResponse mapCart(CustomerCart cart,List<ValidationWarning> initial,HttpServletRequest request){List<ValidationWarning>warnings=new ArrayList<>(initial);List<CartItemResponse> output=new ArrayList<>();for(CustomerCartItem item:cartItems.findByCartIdOrderByIdAsc(cart.getId())){try{Validated value=validated(item.getProductId(),item.getVariationId(),false);Product p=value.product();ProductVariation v=value.variation();BigDecimal price=offerPricing.bestPrice(p.getId(),p.getSellingPrice()).currentPrice().add(v==null?BigDecimal.ZERO:money(v.getAdditionalPrice()));boolean available=value.available()>0;String message=available?null:"Product is out of stock.";if(!available)warnings.add(warn(p.getId(),item.getVariationId(),"PRODUCT_OUT_OF_STOCK",message));output.add(new CartItemResponse(item.getId(),p.getId(),item.getVariationId(),p.getProductName(),p.getProductCode(),v==null?p.getSku():v.getSku(),v==null?null:v.getVariationName(),images.resolve(v!=null&&v.getImageUrl()!=null?v.getImageUrl():p.getImageUrl(),request),price,item.getQuantity(),price.multiply(BigDecimal.valueOf(item.getQuantity())),stockLabel(p,value.available()),available,message));}catch(CustomerAuthException ex){warnings.add(warn(item.getProductId(),item.getVariationId(),ex.code(),ex.getMessage()));}}
 BigDecimal subtotal=output.stream().map(CartItemResponse::lineSubtotal).reduce(BigDecimal.ZERO,BigDecimal::add);int quantity=output.stream().mapToInt(CartItemResponse::quantity).sum();return new CartResponse(cart.getId(),output,output.size(),quantity,subtotal,warnings,cart.getUpdatedAt());}
 private WishlistResponse mapWishlist(CustomerWishlist list,List<ValidationWarning> initial,HttpServletRequest request){List<ValidationWarning>warnings=new ArrayList<>(initial);List<WishlistItemResponse> output=new ArrayList<>();for(CustomerWishlistItem item:wishlistItems.findByWishlistIdOrderByIdAsc(list.getId())){try{Validated value=validated(item.getProductId(),null,false);Product p=value.product();String category=categories.findById(p.getCategoryId()).map(Category::getCategoryName).orElse(null);output.add(new WishlistItemResponse(p.getId(),p.getProductName(),images.resolve(p.getImageUrl(),request),money(p.getSellingPrice()),stockLabel(p,value.available()),category));}catch(CustomerAuthException ex){warnings.add(warn(item.getProductId(),null,ex.code(),ex.getMessage()));}}return new WishlistResponse(list.getId(),output,output.size(),warnings,list.getUpdatedAt());}
 private String stockLabel(Product p,long available){if(available<=0)return "Out of Stock";return available<=(p.getReorderLevel()==null?0:p.getReorderLevel())?"Low Stock":"In Stock";}
 private BigDecimal money(BigDecimal value){return value==null?BigDecimal.ZERO:value;}
 private ValidationWarning warn(Long p,Long v,String c,String m){return new ValidationWarning(p,v,c,m);}
 private void saveReceipt(Long account,String type,String requestId){ShoppingMergeReceipt r=new ShoppingMergeReceipt();r.setCustomerAccountId(account);r.setMergeType(type);r.setRequestId(requestId);receipts.saveAndFlush(r);}
 private CustomerAuthException error(HttpStatus status,String code,String message){return new CustomerAuthException(status,code,message);}
 private record Validated(Product product,ProductVariation variation,long available){}
}
