package com.trademaster.ims.mobile.offers.service;

import com.trademaster.ims.mobile.catalog.dto.*;import com.trademaster.ims.mobile.catalog.service.MobileImageUrlService;import com.trademaster.ims.mobile.common.exception.MobileResourceNotFoundException;import com.trademaster.ims.mobile.common.exception.MobileValidationException;import com.trademaster.ims.mobile.common.response.MobileFieldError;import com.trademaster.ims.mobile.offers.dto.OfferDtos.*;import com.trademaster.ims.mobile.offers.model.*;import com.trademaster.ims.mobile.offers.repository.*;import com.trademaster.ims.model.*;import com.trademaster.ims.repository.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;

@Service @Transactional(readOnly=true)
public class MobileOfferService{
 private final MobileOfferRepository offers;private final MobileOfferProductRepository offerProducts;private final ProductRepository products;private final CategoryRepository categories;private final UnitRepository units;private final InventoryRepository inventory;private final MobileImageUrlService images;private final OfferPricingService pricing;
 public MobileOfferService(MobileOfferRepository offers,MobileOfferProductRepository offerProducts,ProductRepository products,CategoryRepository categories,UnitRepository units,InventoryRepository inventory,MobileImageUrlService images,OfferPricingService pricing){this.offers=offers;this.offerProducts=offerProducts;this.products=products;this.categories=categories;this.units=units;this.inventory=inventory;this.images=images;this.pricing=pricing;}
 public List<OfferSummary> list(HttpServletRequest req){return offers.findVisibleActive(Instant.now()).stream().map(o->summary(o,req)).toList();}
 public OfferDetail detail(long id,HttpServletRequest req){MobileOffer o=activeOffer(id);return new OfferDetail(o.getId(),o.getCode(),o.getTitle(),o.getSubtitle(),o.getDescription(),images.resolve(o.getBannerUrl(),req),o.getChannel(),o.getStartAt(),o.getEndAt(),offerProducts.countByOfferIdAndActiveTrue(o.getId()));}
 public OfferProductPage products(long offerId,int page,int size,HttpServletRequest req){if(page<0||size<1||size>100)throw new MobileValidationException(List.of(new MobileFieldError("size","Size must be between 1 and 100.")));MobileOffer offer=activeOffer(offerId);List<MobileOfferProduct> mappings=offerProducts.findByOfferIdAndActiveTrueOrderByDisplayOrderAscIdAsc(offer.getId());List<OfferProduct> all=mappings.stream().map(op->product(op,offer,req)).flatMap(Optional::stream).toList();int from=Math.min(page*size,all.size());int to=Math.min(from+size,all.size());List<OfferProduct> content=all.subList(from,to);int totalPages=all.isEmpty()?0:(int)Math.ceil((double)all.size()/size);return new OfferProductPage(content,page,size,all.size(),totalPages,page==0,to>=all.size());}
 private Optional<OfferProduct> product(MobileOfferProduct op,MobileOffer offer,HttpServletRequest req){Optional<Product> found=products.findByIdAndStatus(op.getProductId(),Product.ProductStatus.ACTIVE);if(found.isEmpty())return Optional.empty();Product p=found.get();OfferPricingService.OfferPrice price=pricing.price(op,p.getSellingPrice());Map<Long,Category> cm=byId(categories.findAllById(p.getCategoryId()==null?List.of():List.of(p.getCategoryId())),Category::getCategoryId);Map<Long,Unit> um=byId(units.findAllById(p.getBaseUnitId()==null?List.of():List.of(p.getBaseUnitId())),Unit::getUnitId);long stock=inventory.aggregateAvailableByProductIds(List.of(p.getId())).stream().findFirst().map(InventoryRepository.ProductStockTotal::getAvailableQuantity).orElse(0L);return Optional.of(new OfferProduct(p.getId(),p.getProductCode(),p.getSku(),p.getProductName(),p.getDescription(),price.currentPrice(),price.originalPrice(),price.savingsAmount(),price.savingsLabel(),p.getTaxRate(),images.resolve(p.getImageUrl(),req),category(cm.get(p.getCategoryId())),unit(um.get(p.getBaseUnitId())),availability(p,stock),offer.getId(),offer.getTitle()));}
 private MobileOffer activeOffer(long id){return offers.findVisibleActiveById(id,Instant.now()).orElseThrow(()->new MobileResourceNotFoundException("Offer is unavailable."));}
 private OfferSummary summary(MobileOffer o,HttpServletRequest req){return new OfferSummary(o.getId(),o.getCode(),o.getTitle(),o.getSubtitle(),o.getDescription(),images.resolve(o.getBannerUrl(),req),o.getChannel(),o.getStartAt(),o.getEndAt(),offerProducts.countByOfferIdAndActiveTrue(o.getId()));}
 private MobileCategorySummaryResponse category(Category c){return c==null?null:new MobileCategorySummaryResponse(c.getCategoryId(),c.getCategoryName(),c.getDescription(),c.getParentCategoryId(),c.getParentCategoryId()==null,Boolean.TRUE.equals(c.getStatus()));}
 private MobileUnitSummaryResponse unit(Unit u){return u==null?null:new MobileUnitSummaryResponse(u.getUnitId(),u.getUnitName(),u.getUnitCode());}
 private MobileStockAvailabilityResponse availability(Product p,long available){if(available<=0)return new MobileStockAvailabilityResponse(false,"Out of Stock");int reorder=p.getReorderLevel()==null?0:p.getReorderLevel();return new MobileStockAvailabilityResponse(true,available<=reorder?"Low Stock":"In Stock");}
 private <T>Map<Long,T>byId(Iterable<T> values,Function<T,Long> id){Map<Long,T>m=new HashMap<>();values.forEach(v->m.put(id.apply(v),v));return m;}
}