package com.trademaster.ims.mobile.offers.service;

import com.trademaster.ims.mobile.offers.model.*;import com.trademaster.ims.mobile.offers.repository.*;import com.trademaster.ims.model.Product;import com.trademaster.ims.repository.ProductRepository;import org.springframework.boot.context.event.ApplicationReadyEvent;import org.springframework.context.event.EventListener;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.*;import java.util.*;

@Service
public class OfferSeedService{
 private final MobileOfferRepository offers;private final MobileOfferProductRepository offerProducts;private final ProductRepository products;
 public OfferSeedService(MobileOfferRepository offers,MobileOfferProductRepository offerProducts,ProductRepository products){this.offers=offers;this.offerProducts=offerProducts;this.products=products;}
 @EventListener(ApplicationReadyEvent.class) @Transactional public void seed(){if(offers.count()>0)return;List<Product> real=products.findByStatus(Product.ProductStatus.ACTIVE).stream().filter(p->p.getProductName()!=null&&!p.getProductName().startsWith("Phase 11 Test")&&p.getProductCode()!=null&&!p.getProductCode().startsWith("P11-")&&!p.getProductCode().startsWith("PHASE11_FIXTURE_")).limit(8).toList();if(real.isEmpty())return;MobileOffer offer=new MobileOffer();offer.setCode("WELCOME_ONLINE_DEALS");offer.setTitle("Online Tech Deals");offer.setSubtitle("Limited-time savings on selected TechSmart products");offer.setDescription("Shop selected active catalog products with backend-authoritative offer pricing.");offer.setChannel("Online");offer.setBannerUrl(null);offer.setStartAt(Instant.now().minus(Duration.ofDays(1)));offer.setEndAt(Instant.now().plus(Duration.ofDays(30)));offer.setDisplayOrder(1);offer=offers.save(offer);int order=0;for(Product p:real){MobileOfferProduct op=new MobileOfferProduct();op.setOfferId(offer.getId());op.setProductId(p.getId());op.setDiscountType(MobileOfferProduct.DiscountType.PERCENT);op.setDiscountValue(new BigDecimal(order%2==0?"10":"7.5"));op.setDisplayOrder(order++);offerProducts.save(op);}}
}