package com.trademaster.ims.mobile.fulfillment.controller;
import com.trademaster.ims.mobile.fulfillment.dto.FulfillmentDtos.*;import com.trademaster.ims.mobile.fulfillment.service.OrderFulfillmentService;import jakarta.validation.Valid;import org.springframework.data.domain.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/orders/fulfillment") @PreAuthorize("hasRole('ADMIN') or hasRole('SUPER_ADMIN') or hasRole('MANAGER') or hasAuthority('ORDER_FULFILLMENT_MANAGE') or hasAuthority('INVENTORY_MANAGE')") public class OrderFulfillmentController{private final OrderFulfillmentService s;public OrderFulfillmentController(OrderFulfillmentService s){this.s=s;}private String actor(Authentication a){return a==null?"system":a.getName();}
 @GetMapping public FulfillmentPage list(@RequestParam(required=false)String status,@RequestParam(required=false)String orderNumber,@RequestParam(required=false)String paymentStatus,@RequestParam(required=false)String dateFrom,@RequestParam(required=false)String dateTo,@RequestParam(required=false)String deliveryPartner,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return s.list(status,orderNumber,paymentStatus,dateFrom,dateTo,deliveryPartner,PageRequest.of(Math.max(0,page),Math.max(1,Math.min(size,50)),Sort.by("updatedAt").descending()));}
 @GetMapping("/{orderNumber}") public FulfillmentDetail detail(@PathVariable String orderNumber){return s.adminDetail(orderNumber);} @PostMapping("/{orderNumber}/start-processing") public FulfillmentDetail start(@PathVariable String orderNumber,@Valid @RequestBody(required=false)TransitionRequest q,Authentication a){return s.startProcessing(orderNumber,q,actor(a));}
 @PostMapping("/{orderNumber}/pack") public FulfillmentDetail pack(@PathVariable String orderNumber,@Valid @RequestBody(required=false)TransitionRequest q,Authentication a){return s.pack(orderNumber,q,actor(a));}
 @PostMapping("/{orderNumber}/ship") public FulfillmentDetail ship(@PathVariable String orderNumber,@Valid @RequestBody(required=false)TransitionRequest q,Authentication a){return s.ship(orderNumber,q,actor(a));}
 @PostMapping("/{orderNumber}/out-for-delivery") public FulfillmentDetail out(@PathVariable String orderNumber,@Valid @RequestBody(required=false)TransitionRequest q,Authentication a){return s.outForDelivery(orderNumber,q,actor(a));}
 @PostMapping("/{orderNumber}/deliver") public FulfillmentDetail deliver(@PathVariable String orderNumber,@Valid @RequestBody(required=false)TransitionRequest q,Authentication a){return s.deliver(orderNumber,q,actor(a));}
 @PostMapping("/{orderNumber}/delivery-event") public FulfillmentDetail event(@PathVariable String orderNumber,@Valid @RequestBody DeliveryEventRequest q,Authentication a){return s.addEvent(orderNumber,q,actor(a));}}